# ######################################################################## 
# Copyright (C) 2025 Altera Corporation.
# SPDX-License-Identifier: MIT
# ######################################################################## 

# TCL File Generated by Component Editor 23.4
# Wed Nov 29 01:33:46 PST 2023
# DO NOT MODIFY


# 
# address_remapper "address_remapper" v1.0
#  2023.11.29.01:33:46
# 
# 

# 
# request TCL package from ACDS 23.4
# 
package require -exact qsys 23.4


# 
# module address_remapper
# 
set_module_property DESCRIPTION ""
set_module_property NAME address_remapper
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME address_remapper
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL address_remapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file address_remapper.sv SYSTEM_VERILOG PATH ../src/custom_rtl/address_remapper/address_remapper.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL address_remapper
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file address_remapper.sv SYSTEM_VERILOG PATH ../src/custom_rtl/address_remapper/address_remapper.sv


# 
# parameters
# 
add_parameter IN_ADDR_WIDTH INTEGER 21
set_parameter_property IN_ADDR_WIDTH DEFAULT_VALUE 21
set_parameter_property IN_ADDR_WIDTH DISPLAY_NAME IN_ADDR_WIDTH
set_parameter_property IN_ADDR_WIDTH UNITS None
set_parameter_property IN_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property IN_ADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property IN_ADDR_WIDTH HDL_PARAMETER true
set_parameter_property IN_ADDR_WIDTH EXPORT true
add_parameter IN_DATA_WIDTH INTEGER 32 ""
set_parameter_property IN_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property IN_DATA_WIDTH DISPLAY_NAME IN_DATA_WIDTH
set_parameter_property IN_DATA_WIDTH UNITS None
set_parameter_property IN_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property IN_DATA_WIDTH DESCRIPTION ""
set_parameter_property IN_DATA_WIDTH AFFECTS_GENERATION false
set_parameter_property IN_DATA_WIDTH HDL_PARAMETER true
set_parameter_property IN_DATA_WIDTH EXPORT true
add_parameter OUT_ADDR_WIDTH INTEGER 32
set_parameter_property OUT_ADDR_WIDTH DEFAULT_VALUE 32
set_parameter_property OUT_ADDR_WIDTH DISPLAY_NAME OUT_ADDR_WIDTH
set_parameter_property OUT_ADDR_WIDTH UNITS None
set_parameter_property OUT_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property OUT_ADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property OUT_ADDR_WIDTH HDL_PARAMETER true
set_parameter_property OUT_ADDR_WIDTH EXPORT true
add_parameter OUT_DATA_WIDTH INTEGER 32 ""
set_parameter_property OUT_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property OUT_DATA_WIDTH DISPLAY_NAME OUT_DATA_WIDTH
set_parameter_property OUT_DATA_WIDTH UNITS None
set_parameter_property OUT_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property OUT_DATA_WIDTH DESCRIPTION ""
set_parameter_property OUT_DATA_WIDTH AFFECTS_GENERATION false
set_parameter_property OUT_DATA_WIDTH HDL_PARAMETER true
set_parameter_property OUT_DATA_WIDTH EXPORT true
add_parameter RESP_WIDTH INTEGER 2
set_parameter_property RESP_WIDTH DEFAULT_VALUE 2
set_parameter_property RESP_WIDTH DISPLAY_NAME RESP_WIDTH
set_parameter_property RESP_WIDTH UNITS None
set_parameter_property RESP_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RESP_WIDTH AFFECTS_GENERATION false
set_parameter_property RESP_WIDTH HDL_PARAMETER true
set_parameter_property RESP_WIDTH EXPORT true


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""
set_interface_property clk IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clk SV_INTERFACE_TYPE ""
set_interface_property clk SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clk clk clk Input 1


# 
# connection point rst_n
# 
add_interface rst_n reset end
set_interface_property rst_n associatedClock clk
set_interface_property rst_n synchronousEdges DEASSERT
set_interface_property rst_n ENABLED true
set_interface_property rst_n EXPORT_OF ""
set_interface_property rst_n PORT_NAME_MAP ""
set_interface_property rst_n CMSIS_SVD_VARIABLES ""
set_interface_property rst_n SVD_ADDRESS_GROUP ""
set_interface_property rst_n IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property rst_n SV_INTERFACE_TYPE ""
set_interface_property rst_n SV_INTERFACE_MODPORT_TYPE ""

add_interface_port rst_n rst_n reset_n Input 1


# 
# connection point address_remapper_in
# 
add_interface address_remapper_in avalon end
set_interface_property address_remapper_in addressGroup 0
set_interface_property address_remapper_in addressUnits SYMBOLS
set_interface_property address_remapper_in associatedClock clk
set_interface_property address_remapper_in associatedReset rst_n
set_interface_property address_remapper_in bitsPerSymbol 8
set_interface_property address_remapper_in bridgedAddressOffset ""
set_interface_property address_remapper_in bridgesToMaster ""
set_interface_property address_remapper_in burstOnBurstBoundariesOnly false
set_interface_property address_remapper_in burstcountUnits WORDS
set_interface_property address_remapper_in explicitAddressSpan 0
set_interface_property address_remapper_in holdTime 0
set_interface_property address_remapper_in linewrapBursts false
set_interface_property address_remapper_in maximumPendingReadTransactions 1
set_interface_property address_remapper_in maximumPendingWriteTransactions 1
set_interface_property address_remapper_in minimumResponseLatency 1
set_interface_property address_remapper_in readLatency 0
set_interface_property address_remapper_in readWaitTime 1
set_interface_property address_remapper_in setupTime 0
set_interface_property address_remapper_in timingUnits Cycles
set_interface_property address_remapper_in transparentBridge false
set_interface_property address_remapper_in waitrequestAllowance 0
set_interface_property address_remapper_in writeWaitTime 0
set_interface_property address_remapper_in dfhFeatureGuid 0
set_interface_property address_remapper_in dfhGroupId 0
set_interface_property address_remapper_in dfhParameterId ""
set_interface_property address_remapper_in dfhParameterName ""
set_interface_property address_remapper_in dfhParameterVersion ""
set_interface_property address_remapper_in dfhParameterData ""
set_interface_property address_remapper_in dfhParameterDataLength ""
set_interface_property address_remapper_in dfhFeatureMajorVersion 0
set_interface_property address_remapper_in dfhFeatureMinorVersion 0
set_interface_property address_remapper_in dfhFeatureId 35
set_interface_property address_remapper_in ENABLED true
set_interface_property address_remapper_in EXPORT_OF ""
set_interface_property address_remapper_in PORT_NAME_MAP ""
set_interface_property address_remapper_in CMSIS_SVD_VARIABLES ""
set_interface_property address_remapper_in SVD_ADDRESS_GROUP ""
set_interface_property address_remapper_in IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property address_remapper_in SV_INTERFACE_TYPE ""
set_interface_property address_remapper_in SV_INTERFACE_MODPORT_TYPE ""

add_interface_port address_remapper_in hps_burstcount_i burstcount Input 1
add_interface_port address_remapper_in hps_writedata_i writedata Input "((IN_DATA_WIDTH - 1)) - (0) + 1"
add_interface_port address_remapper_in hps_address_i address Input "((IN_ADDR_WIDTH - 1)) - (0) + 1"
add_interface_port address_remapper_in hps_write_i write Input 1
add_interface_port address_remapper_in hps_read_i read Input 1
add_interface_port address_remapper_in hps_byteenable_i byteenable Input "(((IN_DATA_WIDTH / 8) - 1)) - (0) + 1"
add_interface_port address_remapper_in hps_debugaccess_i debugaccess Input 1
add_interface_port address_remapper_in hps_waitrequest_o waitrequest Output 1
add_interface_port address_remapper_in hps_readdata_o readdata Output "((IN_DATA_WIDTH - 1)) - (0) + 1"
add_interface_port address_remapper_in hps_readdatavalid_o readdatavalid Output 1
add_interface_port address_remapper_in hps_resp_o response Output 2
add_interface_port address_remapper_in hps_writerespvalid_o writeresponsevalid Output 1
set_interface_assignment address_remapper_in embeddedsw.configuration.isFlash 0
set_interface_assignment address_remapper_in embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment address_remapper_in embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment address_remapper_in embeddedsw.configuration.isPrintableDevice 0


# 
# connection point address_remapper_out
# 
add_interface address_remapper_out avalon start
set_interface_property address_remapper_out addressGroup 0
set_interface_property address_remapper_out addressUnits SYMBOLS
set_interface_property address_remapper_out associatedClock clk
set_interface_property address_remapper_out associatedReset rst_n
set_interface_property address_remapper_out bitsPerSymbol 8
set_interface_property address_remapper_out burstOnBurstBoundariesOnly false
set_interface_property address_remapper_out burstcountUnits WORDS
set_interface_property address_remapper_out doStreamReads false
set_interface_property address_remapper_out doStreamWrites false
set_interface_property address_remapper_out holdTime 0
set_interface_property address_remapper_out linewrapBursts false
set_interface_property address_remapper_out maximumPendingReadTransactions 0
set_interface_property address_remapper_out maximumPendingWriteTransactions 0
set_interface_property address_remapper_out minimumResponseLatency 1
set_interface_property address_remapper_out readLatency 0
set_interface_property address_remapper_out readWaitTime 1
set_interface_property address_remapper_out setupTime 0
set_interface_property address_remapper_out timingUnits Cycles
set_interface_property address_remapper_out waitrequestAllowance 0
set_interface_property address_remapper_out writeWaitTime 0
set_interface_property address_remapper_out ENABLED true
set_interface_property address_remapper_out EXPORT_OF ""
set_interface_property address_remapper_out PORT_NAME_MAP ""
set_interface_property address_remapper_out CMSIS_SVD_VARIABLES ""
set_interface_property address_remapper_out SVD_ADDRESS_GROUP ""
set_interface_property address_remapper_out IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property address_remapper_out SV_INTERFACE_TYPE ""
set_interface_property address_remapper_out SV_INTERFACE_MODPORT_TYPE ""

add_interface_port address_remapper_out mcdma_waitrequest_i waitrequest Input 1
add_interface_port address_remapper_out mcdma_readdata_i readdata Input "((OUT_DATA_WIDTH - 1)) - (0) + 1"
add_interface_port address_remapper_out mcdma_readdatavalid_i readdatavalid Input 1
add_interface_port address_remapper_out mcdma_burstcount_o burstcount Output 1
add_interface_port address_remapper_out mcdma_writedata_o writedata Output "((OUT_DATA_WIDTH - 1)) - (0) + 1"
add_interface_port address_remapper_out mcdma_address_o address Output "((OUT_ADDR_WIDTH - 1)) - (0) + 1"
add_interface_port address_remapper_out mcdma_write_o write Output 1
add_interface_port address_remapper_out mcdma_read_o read Output 1
add_interface_port address_remapper_out mcdma_byteenable_o byteenable Output "(((OUT_DATA_WIDTH / 8) - 1)) - (0) + 1"
add_interface_port address_remapper_out mcdma_resp_i response Input 2
add_interface_port address_remapper_out mcdma_writerespvalid_i writeresponsevalid Input 1

