# ######################################################################## 
# Copyright (C) 2025 Altera Corporation.
# SPDX-License-Identifier: MIT
# ######################################################################## 
#
# TCL File Generated by Component Editor 24.3
# Tue Sep 17 01:56:35 PDT 2024
# DO NOT MODIFY


# 
# config_timeout "config_timeout" v1.0
#  2024.09.17.01:56:35
# 
# 

# 
# request TCL package from ACDS 24.3
# 
package require -exact qsys 24.3


# 
# module config_timeout
# 
set_module_property DESCRIPTION ""
set_module_property NAME config_timeout
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME config_timeout
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL configuration_timeout_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file configuration_timeout_top.sv SYSTEM_VERILOG PATH ../src/custom_rtl/config_timeout/configuration_timeout_top.sv TOP_LEVEL_FILE
add_fileset_file configuration_timeout.sv SYSTEM_VERILOG PATH ../src/custom_rtl/config_timeout/configuration_timeout.sv
add_fileset_file csr_register.sv SYSTEM_VERILOG PATH ../src/custom_rtl/config_timeout/csr_register.sv
add_fileset_file multiplexer.sv SYSTEM_VERILOG PATH ../src/custom_rtl/config_timeout/multiplexer.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL configuration_timeout_top
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file configuration_timeout_top.sv SYSTEM_VERILOG PATH ../src/custom_rtl/config_timeout/configuration_timeout_top.sv
add_fileset_file configuration_timeout.sv SYSTEM_VERILOG PATH ../src/custom_rtl/config_timeout/configuration_timeout.sv
add_fileset_file csr_register.sv SYSTEM_VERILOG PATH ../src/custom_rtl/config_timeout/csr_register.sv
add_fileset_file multiplexer.sv SYSTEM_VERILOG PATH ../src/custom_rtl/config_timeout/multiplexer.sv


# 
# parameters
# 
add_parameter ADDR_WIDTH INTEGER 14
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 14
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
set_parameter_property ADDR_WIDTH EXPORT true
add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH AFFECTS_GENERATION false
set_parameter_property DATA_WIDTH HDL_PARAMETER true
set_parameter_property DATA_WIDTH EXPORT true
add_parameter RESP_WIDTH INTEGER 2
set_parameter_property RESP_WIDTH DEFAULT_VALUE 2
set_parameter_property RESP_WIDTH DISPLAY_NAME RESP_WIDTH
set_parameter_property RESP_WIDTH UNITS None
set_parameter_property RESP_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RESP_WIDTH AFFECTS_GENERATION false
set_parameter_property RESP_WIDTH HDL_PARAMETER true
set_parameter_property RESP_WIDTH EXPORT true
add_parameter CSR_ADDR_WIDTH INTEGER 8
set_parameter_property CSR_ADDR_WIDTH DEFAULT_VALUE 8
set_parameter_property CSR_ADDR_WIDTH DISPLAY_NAME CSR_ADDR_WIDTH
set_parameter_property CSR_ADDR_WIDTH UNITS None
set_parameter_property CSR_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CSR_ADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property CSR_ADDR_WIDTH HDL_PARAMETER true
set_parameter_property CSR_ADDR_WIDTH EXPORT true
add_parameter CSR_DATA_WIDTH INTEGER 32
set_parameter_property CSR_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property CSR_DATA_WIDTH DISPLAY_NAME CSR_DATA_WIDTH
set_parameter_property CSR_DATA_WIDTH UNITS None
set_parameter_property CSR_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CSR_DATA_WIDTH AFFECTS_GENERATION false
set_parameter_property CSR_DATA_WIDTH HDL_PARAMETER true
set_parameter_property CSR_DATA_WIDTH EXPORT true
add_parameter CSR_BYTE_ENABLE_WIDTH INTEGER 4
set_parameter_property CSR_BYTE_ENABLE_WIDTH DEFAULT_VALUE 4
set_parameter_property CSR_BYTE_ENABLE_WIDTH DISPLAY_NAME CSR_BYTE_ENABLE_WIDTH
set_parameter_property CSR_BYTE_ENABLE_WIDTH UNITS None
set_parameter_property CSR_BYTE_ENABLE_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CSR_BYTE_ENABLE_WIDTH AFFECTS_GENERATION false
set_parameter_property CSR_BYTE_ENABLE_WIDTH HDL_PARAMETER true
set_parameter_property CSR_BYTE_ENABLE_WIDTH EXPORT true
add_parameter LTSSM_STATE_WIDTH INTEGER 6
set_parameter_property LTSSM_STATE_WIDTH DEFAULT_VALUE 6
set_parameter_property LTSSM_STATE_WIDTH DISPLAY_NAME LTSSM_STATE_WIDTH
set_parameter_property LTSSM_STATE_WIDTH UNITS None
set_parameter_property LTSSM_STATE_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LTSSM_STATE_WIDTH AFFECTS_GENERATION false
set_parameter_property LTSSM_STATE_WIDTH HDL_PARAMETER true
set_parameter_property LTSSM_STATE_WIDTH EXPORT true


# 
# display items
# 


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressGroup 0
set_interface_property csr addressUnits SYMBOLS
set_interface_property csr associatedClock clk_i
set_interface_property csr associatedReset rstn_i
set_interface_property csr bitsPerSymbol 8
set_interface_property csr bridgedAddressOffset ""
set_interface_property csr bridgesToMaster ""
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 1
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr minimumResponseLatency 1
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr transparentBridge false
set_interface_property csr waitrequestAllowance 0
set_interface_property csr writeWaitTime 0
set_interface_property csr dfhFeatureGuid 0
set_interface_property csr dfhGroupId 0
set_interface_property csr dfhParameterId ""
set_interface_property csr dfhParameterName ""
set_interface_property csr dfhParameterVersion ""
set_interface_property csr dfhParameterData ""
set_interface_property csr dfhParameterDataLength ""
set_interface_property csr dfhFeatureMajorVersion 0
set_interface_property csr dfhFeatureMinorVersion 0
set_interface_property csr dfhFeatureId 35
set_interface_property csr dfhFeatureType 3
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""
set_interface_property csr IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property csr SV_INTERFACE_TYPE ""
set_interface_property csr SV_INTERFACE_MODPORT_TYPE ""

add_interface_port csr csr_address_i address Input "((CSR_ADDR_WIDTH - 1)) - (0) + 1"
add_interface_port csr csr_read_i read Input 1
add_interface_port csr csr_write_i write Input 1
add_interface_port csr csr_writedata_i writedata Input "((CSR_DATA_WIDTH - 1)) - (0) + 1"
add_interface_port csr csr_burstcount_i burstcount Input 1
add_interface_port csr csr_byteenable_i byteenable Input "(((CSR_DATA_WIDTH / 8) - 1)) - (0) + 1"
add_interface_port csr csr_debugaccess_i debugaccess Input 1
add_interface_port csr csr_readdatavalid_o readdatavalid Output 1
add_interface_port csr csr_readdata_o readdata Output "((CSR_DATA_WIDTH - 1)) - (0) + 1"
add_interface_port csr csr_waitrequest_o waitrequest Output 1
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk_i
# 
add_interface clk_i clock end
set_interface_property clk_i ENABLED true
set_interface_property clk_i EXPORT_OF ""
set_interface_property clk_i PORT_NAME_MAP ""
set_interface_property clk_i CMSIS_SVD_VARIABLES ""
set_interface_property clk_i SVD_ADDRESS_GROUP ""
set_interface_property clk_i IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clk_i SV_INTERFACE_TYPE ""
set_interface_property clk_i SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clk_i clk_i clk Input 1


# 
# connection point rstn_i
# 
add_interface rstn_i reset end
set_interface_property rstn_i associatedClock clk_i
set_interface_property rstn_i synchronousEdges DEASSERT
set_interface_property rstn_i ENABLED true
set_interface_property rstn_i EXPORT_OF ""
set_interface_property rstn_i PORT_NAME_MAP ""
set_interface_property rstn_i CMSIS_SVD_VARIABLES ""
set_interface_property rstn_i SVD_ADDRESS_GROUP ""
set_interface_property rstn_i IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property rstn_i SV_INTERFACE_TYPE ""
set_interface_property rstn_i SV_INTERFACE_MODPORT_TYPE ""

add_interface_port rstn_i rstn_i reset_n Input 1


# 
# connection point hip_status
# 
add_interface hip_status conduit end
set_interface_property hip_status associatedClock ""
set_interface_property hip_status associatedReset ""
set_interface_property hip_status ENABLED true
set_interface_property hip_status EXPORT_OF ""
set_interface_property hip_status PORT_NAME_MAP ""
set_interface_property hip_status CMSIS_SVD_VARIABLES ""
set_interface_property hip_status SVD_ADDRESS_GROUP ""
set_interface_property hip_status IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property hip_status SV_INTERFACE_TYPE ""
set_interface_property hip_status SV_INTERFACE_MODPORT_TYPE ""

add_interface_port hip_status hip_status_linkup link_up Input 1
add_interface_port hip_status hip_status_dl_up dl_up Input 1
add_interface_port hip_status hip_status_surprise_down_err surprise_down_err Input 1
add_interface_port hip_status hip_status_dl_timer_update dl_timer_update Input 1
add_interface_port hip_status hip_status_ltssm_state_delay ltssm_state_delay Input "((LTSSM_STATE_WIDTH - 1)) - (0) + 1"
add_interface_port hip_status hip_status_ltssm_st_hipfifo_ovrflow ltssm_st_hipfifo_ovrflw Input 1


# 
# connection point config_in
# 
add_interface config_in avalon end
set_interface_property config_in addressGroup 0
set_interface_property config_in addressUnits SYMBOLS
set_interface_property config_in associatedClock clk_i
set_interface_property config_in associatedReset rstn_i
set_interface_property config_in bitsPerSymbol 8
set_interface_property config_in bridgedAddressOffset ""
set_interface_property config_in bridgesToMaster ""
set_interface_property config_in burstOnBurstBoundariesOnly false
set_interface_property config_in burstcountUnits WORDS
set_interface_property config_in explicitAddressSpan 0
set_interface_property config_in holdTime 0
set_interface_property config_in linewrapBursts false
set_interface_property config_in maximumPendingReadTransactions 1
set_interface_property config_in maximumPendingWriteTransactions 1
set_interface_property config_in minimumResponseLatency 1
set_interface_property config_in readLatency 0
set_interface_property config_in readWaitTime 1
set_interface_property config_in setupTime 0
set_interface_property config_in timingUnits Cycles
set_interface_property config_in transparentBridge false
set_interface_property config_in waitrequestAllowance 0
set_interface_property config_in writeWaitTime 0
set_interface_property config_in dfhFeatureGuid 0
set_interface_property config_in dfhGroupId 0
set_interface_property config_in dfhParameterId ""
set_interface_property config_in dfhParameterName ""
set_interface_property config_in dfhParameterVersion ""
set_interface_property config_in dfhParameterData ""
set_interface_property config_in dfhParameterDataLength ""
set_interface_property config_in dfhFeatureMajorVersion 0
set_interface_property config_in dfhFeatureMinorVersion 0
set_interface_property config_in dfhFeatureId 35
set_interface_property config_in dfhFeatureType 3
set_interface_property config_in ENABLED true
set_interface_property config_in EXPORT_OF ""
set_interface_property config_in PORT_NAME_MAP ""
set_interface_property config_in CMSIS_SVD_VARIABLES ""
set_interface_property config_in SVD_ADDRESS_GROUP ""
set_interface_property config_in IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property config_in SV_INTERFACE_TYPE ""
set_interface_property config_in SV_INTERFACE_MODPORT_TYPE ""

add_interface_port config_in hps_address_i address Input "((ADDR_WIDTH - 1)) - (0) + 1"
add_interface_port config_in hps_writedata_i writedata Input "((DATA_WIDTH - 1)) - (0) + 1"
add_interface_port config_in hps_read_i read Input 1
add_interface_port config_in hps_write_i write Input 1
add_interface_port config_in hps_burstcount_i burstcount Input 1
add_interface_port config_in hps_byteenable_i byteenable Input "(((DATA_WIDTH / 8) - 1)) - (0) + 1"
add_interface_port config_in hps_debugaccess_i debugaccess Input 1
add_interface_port config_in hps_waitrequest_o waitrequest Output 1
add_interface_port config_in hps_readdatavalid_o readdatavalid Output 1
add_interface_port config_in hps_readdata_o readdata Output "((DATA_WIDTH - 1)) - (0) + 1"
add_interface_port config_in hps_writerespvalid_o writeresponsevalid Output 1
add_interface_port config_in hps_resp_o response Output "((RESP_WIDTH - 1)) - (0) + 1"
set_interface_assignment config_in embeddedsw.configuration.isFlash 0
set_interface_assignment config_in embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment config_in embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment config_in embeddedsw.configuration.isPrintableDevice 0


# 
# connection point config_out
# 
add_interface config_out avalon start
set_interface_property config_out addressGroup 0
set_interface_property config_out addressUnits SYMBOLS
set_interface_property config_out associatedClock clk_i
set_interface_property config_out associatedReset rstn_i
set_interface_property config_out bitsPerSymbol 8
set_interface_property config_out burstOnBurstBoundariesOnly false
set_interface_property config_out burstcountUnits WORDS
set_interface_property config_out doStreamReads false
set_interface_property config_out doStreamWrites false
set_interface_property config_out holdTime 0
set_interface_property config_out linewrapBursts false
set_interface_property config_out maximumPendingReadTransactions 0
set_interface_property config_out maximumPendingWriteTransactions 0
set_interface_property config_out minimumResponseLatency 1
set_interface_property config_out readLatency 0
set_interface_property config_out readWaitTime 1
set_interface_property config_out setupTime 0
set_interface_property config_out timingUnits Cycles
set_interface_property config_out waitrequestAllowance 0
set_interface_property config_out waitrequestTimeout 1024
set_interface_property config_out writeWaitTime 0
set_interface_property config_out enableConcurrentSubordinateAccess 0
set_interface_property config_out ENABLED true
set_interface_property config_out EXPORT_OF ""
set_interface_property config_out PORT_NAME_MAP ""
set_interface_property config_out CMSIS_SVD_VARIABLES ""
set_interface_property config_out SVD_ADDRESS_GROUP ""
set_interface_property config_out IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property config_out SV_INTERFACE_TYPE ""
set_interface_property config_out SV_INTERFACE_MODPORT_TYPE ""

add_interface_port config_out cs_waitrequest_i waitrequest Input 1
add_interface_port config_out cs_readdatavalid_i readdatavalid Input 1
add_interface_port config_out cs_writerespvalid_i writeresponsevalid Input 1
add_interface_port config_out cs_readdata_i readdata Input "((DATA_WIDTH - 1)) - (0) + 1"
add_interface_port config_out cs_resp_i response Input "((RESP_WIDTH - 1)) - (0) + 1"
add_interface_port config_out cs_address_o address Output "((ADDR_WIDTH - 1)) - (0) + 1"
add_interface_port config_out cs_writedata_o writedata Output "((DATA_WIDTH - 1)) - (0) + 1"
add_interface_port config_out cs_read_o read Output 1
add_interface_port config_out cs_write_o write Output 1
add_interface_port config_out cs_burstcount_o burstcount Output 1
add_interface_port config_out cs_byteenable_o byteenable Output "(((DATA_WIDTH / 8) - 1)) - (0) + 1"

