# ######################################################################## 
# Copyright (C) 2025 Altera Corporation.
# SPDX-License-Identifier: MIT
# ######################################################################## 

# TCL File Generated by Component Editor 24.1
# Tue Sep 24 02:02:17 PDT 2024
# DO NOT MODIFY


# 
# pipeline_stages "pipeline_stages" v1.0
#  2024.09.24.02:02:17
# 
# 

# 
# request TCL package from ACDS 24.1
# 
package require -exact qsys 24.1


# 
# module pipeline_stages
# 
set_module_property DESCRIPTION ""
set_module_property NAME pipeline_stages
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME pipeline_stages
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pipeline_stages
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pipeline_stages.sv SYSTEM_VERILOG PATH ../src/custom_rtl/pipeline_stages/pipeline_stages.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL pipeline_stages
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pipeline_stages.sv SYSTEM_VERILOG PATH ../src/custom_rtl/pipeline_stages/pipeline_stages.sv


# 
# parameters
# 
add_parameter F2H_ADDR_WIDTH INTEGER 16
set_parameter_property F2H_ADDR_WIDTH DEFAULT_VALUE 16
set_parameter_property F2H_ADDR_WIDTH DISPLAY_NAME F2H_ADDR_WIDTH
set_parameter_property F2H_ADDR_WIDTH UNITS None
set_parameter_property F2H_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property F2H_ADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property F2H_ADDR_WIDTH HDL_PARAMETER true
set_parameter_property F2H_ADDR_WIDTH EXPORT true
add_parameter F2H_DATA_WIDTH INTEGER 32
set_parameter_property F2H_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property F2H_DATA_WIDTH DISPLAY_NAME F2H_DATA_WIDTH
set_parameter_property F2H_DATA_WIDTH UNITS None
set_parameter_property F2H_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property F2H_DATA_WIDTH AFFECTS_GENERATION false
set_parameter_property F2H_DATA_WIDTH HDL_PARAMETER true
set_parameter_property F2H_DATA_WIDTH EXPORT true
add_parameter PIPE_STAGES INTEGER 32
set_parameter_property PIPE_STAGES DEFAULT_VALUE 32
set_parameter_property PIPE_STAGES DISPLAY_NAME PIPE_STAGES
set_parameter_property PIPE_STAGES UNITS None
set_parameter_property PIPE_STAGES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PIPE_STAGES AFFECTS_GENERATION false
set_parameter_property PIPE_STAGES HDL_PARAMETER true
set_parameter_property PIPE_STAGES EXPORT true


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""
set_interface_property clk IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clk SV_INTERFACE_TYPE ""
set_interface_property clk SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clk clk clk Input 1


# 
# connection point rst_n
# 
add_interface rst_n reset end
set_interface_property rst_n associatedClock clk
set_interface_property rst_n synchronousEdges DEASSERT
set_interface_property rst_n ENABLED true
set_interface_property rst_n EXPORT_OF ""
set_interface_property rst_n PORT_NAME_MAP ""
set_interface_property rst_n CMSIS_SVD_VARIABLES ""
set_interface_property rst_n SVD_ADDRESS_GROUP ""
set_interface_property rst_n IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property rst_n SV_INTERFACE_TYPE ""
set_interface_property rst_n SV_INTERFACE_MODPORT_TYPE ""

add_interface_port rst_n rst_n reset_n Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressGroup 0
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clk
set_interface_property avalon_master associatedReset rst_n
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master minimumResponseLatency 1
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master waitrequestAllowance 0
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""
set_interface_property avalon_master IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property avalon_master SV_INTERFACE_TYPE ""
set_interface_property avalon_master SV_INTERFACE_MODPORT_TYPE ""

add_interface_port avalon_master m0_avmm_write write Output 1
add_interface_port avalon_master m0_avmm_read read Output 1
add_interface_port avalon_master m0_avmm_address address Output "((F2H_ADDR_WIDTH - 1)) - (0) + 1"
add_interface_port avalon_master m0_avmm_byteenable byteenable Output "(((F2H_DATA_WIDTH / 8) - 1)) - (0) + 1"
add_interface_port avalon_master m0_avmm_writedata writedata Output "((F2H_DATA_WIDTH - 1)) - (0) + 1"
add_interface_port avalon_master m0_avmm_readdatavalid readdatavalid Input 1
add_interface_port avalon_master m0_avmm_readdata readdata Input "((F2H_DATA_WIDTH - 1)) - (0) + 1"
add_interface_port avalon_master m0_avmm_waitrequest waitrequest Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressGroup 0
set_interface_property avalon_slave addressUnits SYMBOLS
set_interface_property avalon_slave associatedClock clk
set_interface_property avalon_slave associatedReset rst_n
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave bridgedAddressOffset ""
set_interface_property avalon_slave bridgesToMaster ""
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 1
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave minimumResponseLatency 1
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave transparentBridge false
set_interface_property avalon_slave waitrequestAllowance 0
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave dfhFeatureGuid 0
set_interface_property avalon_slave dfhGroupId 0
set_interface_property avalon_slave dfhParameterId ""
set_interface_property avalon_slave dfhParameterName ""
set_interface_property avalon_slave dfhParameterVersion ""
set_interface_property avalon_slave dfhParameterData ""
set_interface_property avalon_slave dfhParameterDataLength ""
set_interface_property avalon_slave dfhFeatureMajorVersion 0
set_interface_property avalon_slave dfhFeatureMinorVersion 0
set_interface_property avalon_slave dfhFeatureId 35
set_interface_property avalon_slave dfhFeatureType 3
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""
set_interface_property avalon_slave IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property avalon_slave SV_INTERFACE_TYPE ""
set_interface_property avalon_slave SV_INTERFACE_MODPORT_TYPE ""

add_interface_port avalon_slave s0_avmm_write write Input 1
add_interface_port avalon_slave s0_avmm_read read Input 1
add_interface_port avalon_slave s0_avmm_address address Input "((F2H_ADDR_WIDTH - 1)) - (0) + 1"
add_interface_port avalon_slave s0_avmm_byteenable byteenable Input "(((F2H_DATA_WIDTH / 8) - 1)) - (0) + 1"
add_interface_port avalon_slave s0_avmm_writedata writedata Input "((F2H_DATA_WIDTH - 1)) - (0) + 1"
add_interface_port avalon_slave s0_avmm_readdatavalid readdatavalid Output 1
add_interface_port avalon_slave s0_avmm_readdata readdata Output "((F2H_DATA_WIDTH - 1)) - (0) + 1"
add_interface_port avalon_slave s0_avmm_waitrequest waitrequest Output 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

