# TCL File Generated by Component Editor 24.3
# Tue Sep 17 01:54:38 PDT 2024
# DO NOT MODIFY


# 
# f2h_interface_tester "f2h_interface_tester" v1.0
#  2024.09.17.01:54:38
# 
# 

# 
# request TCL package from ACDS 24.3
# 
package require -exact qsys 24.3


# 
# module f2h_interface_tester
# 
set_module_property DESCRIPTION ""
set_module_property NAME f2h_interface_tester
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "hps f2h"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME f2h_interface_tester
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL f2h_interface_tester
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file csr_registers.sv SYSTEM_VERILOG PATH ../src/custom_rtl/f2h_tester/csr_registers.sv
add_fileset_file f2h_interface_tester.sv SYSTEM_VERILOG PATH ../src/custom_rtl/f2h_tester/f2h_interface_tester.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL f2h_interface_tester
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file csr_registers.sv SYSTEM_VERILOG PATH ../src/custom_rtl/f2h_tester/csr_registers.sv
add_fileset_file f2h_interface_tester.sv SYSTEM_VERILOG PATH ../src/custom_rtl/f2h_tester/f2h_interface_tester.sv


# 
# parameters
# 
add_parameter CSR_ADDR_WIDTH INTEGER 14
set_parameter_property CSR_ADDR_WIDTH DEFAULT_VALUE 14
set_parameter_property CSR_ADDR_WIDTH DISPLAY_NAME CSR_ADDR_WIDTH
set_parameter_property CSR_ADDR_WIDTH UNITS None
set_parameter_property CSR_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CSR_ADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property CSR_ADDR_WIDTH HDL_PARAMETER true
set_parameter_property CSR_ADDR_WIDTH EXPORT true
add_parameter CSR_DATA_WIDTH INTEGER 32
set_parameter_property CSR_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property CSR_DATA_WIDTH DISPLAY_NAME CSR_DATA_WIDTH
set_parameter_property CSR_DATA_WIDTH UNITS None
set_parameter_property CSR_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CSR_DATA_WIDTH AFFECTS_GENERATION false
set_parameter_property CSR_DATA_WIDTH HDL_PARAMETER true
set_parameter_property CSR_DATA_WIDTH EXPORT true
add_parameter F2H_ADDR_WIDTH INTEGER 64
set_parameter_property F2H_ADDR_WIDTH DEFAULT_VALUE 64
set_parameter_property F2H_ADDR_WIDTH DISPLAY_NAME F2H_ADDR_WIDTH
set_parameter_property F2H_ADDR_WIDTH UNITS None
set_parameter_property F2H_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property F2H_ADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property F2H_ADDR_WIDTH HDL_PARAMETER true
set_parameter_property F2H_ADDR_WIDTH EXPORT true
add_parameter F2H_DATA_WIDTH INTEGER 512
set_parameter_property F2H_DATA_WIDTH DEFAULT_VALUE 512
set_parameter_property F2H_DATA_WIDTH DISPLAY_NAME F2H_DATA_WIDTH
set_parameter_property F2H_DATA_WIDTH UNITS None
set_parameter_property F2H_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property F2H_DATA_WIDTH AFFECTS_GENERATION false
set_parameter_property F2H_DATA_WIDTH HDL_PARAMETER true
set_parameter_property F2H_DATA_WIDTH EXPORT true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""
set_interface_property clock IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clock SV_INTERFACE_TYPE ""
set_interface_property clock SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clock clk clk Input 1


# 
# connection point csr_avmm
# 
add_interface csr_avmm avalon end
set_interface_property csr_avmm addressGroup 0
set_interface_property csr_avmm addressUnits SYMBOLS
set_interface_property csr_avmm associatedClock clock
set_interface_property csr_avmm associatedReset reset_sink
set_interface_property csr_avmm bitsPerSymbol 8
set_interface_property csr_avmm bridgedAddressOffset ""
set_interface_property csr_avmm bridgesToMaster ""
set_interface_property csr_avmm burstOnBurstBoundariesOnly false
set_interface_property csr_avmm burstcountUnits WORDS
set_interface_property csr_avmm explicitAddressSpan 0
set_interface_property csr_avmm holdTime 0
set_interface_property csr_avmm linewrapBursts false
set_interface_property csr_avmm maximumPendingReadTransactions 1
set_interface_property csr_avmm maximumPendingWriteTransactions 0
set_interface_property csr_avmm minimumResponseLatency 1
set_interface_property csr_avmm readLatency 0
set_interface_property csr_avmm readWaitTime 1
set_interface_property csr_avmm setupTime 0
set_interface_property csr_avmm timingUnits Cycles
set_interface_property csr_avmm transparentBridge false
set_interface_property csr_avmm waitrequestAllowance 0
set_interface_property csr_avmm writeWaitTime 0
set_interface_property csr_avmm ENABLED true
set_interface_property csr_avmm EXPORT_OF ""
set_interface_property csr_avmm PORT_NAME_MAP ""
set_interface_property csr_avmm CMSIS_SVD_VARIABLES ""
set_interface_property csr_avmm SVD_ADDRESS_GROUP ""
set_interface_property csr_avmm IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property csr_avmm SV_INTERFACE_TYPE ""
set_interface_property csr_avmm SV_INTERFACE_MODPORT_TYPE ""

add_interface_port csr_avmm csr_avmm_write write Input 1
add_interface_port csr_avmm csr_avmm_read read Input 1
add_interface_port csr_avmm csr_avmm_address address Input "((CSR_ADDR_WIDTH - 1)) - (0) + 1"
add_interface_port csr_avmm csr_avmm_writedata writedata Input "((CSR_DATA_WIDTH - 1)) - (0) + 1"
add_interface_port csr_avmm csr_avmm_readdatavalid readdatavalid Output 1
add_interface_port csr_avmm csr_avmm_readdata readdata Output "((CSR_DATA_WIDTH - 1)) - (0) + 1"
add_interface_port csr_avmm csr_avmm_waitrequest waitrequest Output 1
set_interface_assignment csr_avmm embeddedsw.configuration.isFlash 0
set_interface_assignment csr_avmm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr_avmm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr_avmm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressGroup 0
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master minimumResponseLatency 1
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master waitrequestAllowance 0
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""
set_interface_property avalon_master IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property avalon_master SV_INTERFACE_TYPE ""
set_interface_property avalon_master SV_INTERFACE_MODPORT_TYPE ""

add_interface_port avalon_master f2h_avmm_write write Output 1
add_interface_port avalon_master f2h_avmm_read read Output 1
add_interface_port avalon_master f2h_avmm_address address Output "((F2H_ADDR_WIDTH - 1)) - (0) + 1"
add_interface_port avalon_master f2h_avmm_byteenable byteenable Output "(((F2H_DATA_WIDTH / 8) - 1)) - (0) + 1"
add_interface_port avalon_master f2h_avmm_writedata writedata Output "((F2H_DATA_WIDTH - 1)) - (0) + 1"
add_interface_port avalon_master f2h_avmm_readdatavalid readdatavalid Input 1
add_interface_port avalon_master f2h_avmm_readdata readdata Input "((F2H_DATA_WIDTH - 1)) - (0) + 1"
add_interface_port avalon_master f2h_avmm_waitrequest waitrequest Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""
set_interface_property reset_sink IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property reset_sink SV_INTERFACE_TYPE ""
set_interface_property reset_sink SV_INTERFACE_MODPORT_TYPE ""

add_interface_port reset_sink rst_n reset_n Input 1

