set_global_assignment -name IP_FILE ../src/ip/qsys_top/clk_100.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/rst_in.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/user_rst_clkgate_0.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/sysid.ip
#set_global_assignment -name IP_FILE ../src/ip/qsys_top/clk_125.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/agilex_hps.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/emif_hps.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/emif_calbus_0.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/qsys_top_iopll_0.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/qsys_top_reset_bridge_0.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/qsys_top_reset_bridge_1.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/qsys_top_clock_bridge_1.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/qsys_top_intel_cache_coherency_translator_0.ip
set_global_assignment -name IP_FILE ../src/ip/qsys_top/qsys_top_clock_bridge_0.ip
set_global_assignment -name QSYS_FILE ../src/qsys/qsys_top.qsys

#set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/Pcie_rp_subsystem_address_span_extender_0.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/Pcie_rp_subsystem_address_span_extender_1.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/Pcie_rp_subsystem_clock_bridge_1.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/Pcie_rp_subsystem_mm_bridge_2.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/Pcie_rp_subsystem_reset_bridge_2.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/Pcie_rp_subsystem_mm_bridge_7.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/Pcie_rp_subsystem_mm_bridge_6.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/Pcie_rp_subsystem_performance_counter_0.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/Pcie_rp_subsystem_mm_ccb_1.ip
#set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/Pcie_rp_subsystem_mm_ccb_2.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/Pcie_rp_subsystem_mm_ccb_0.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/Pcie_rp_subsystem_config_timeout_0.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/Pcie_rp_subsystem_mm_bridge_5.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/Pcie_rp_subsystem_f2h_interface_tester_0.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/subsys_pcie_iopll_0.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/subsys_pcie_clock_bridge_0.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/subsys_pcie_reset_bridge_0.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/subsys_pcie_mm_ccb_0.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/subsys_pcie_mm_ccb_1.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/subsys_pcie_reset_bridge_1.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/subsys_pcie_clock_bridge_1.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/subsys_pcie_intel_pcie_ptile_mcdma_0.ip
#set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/Pcie_rp_address_extender_2gb_1.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/Pcie_mm_ccb_6gb_1.ip
set_global_assignment -name QSYS_FILE ../src/qsys/subsys_pcie.qsys
#set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/msi_ordering_igr_avmm_cdc.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/msi_ordering_egr_avmm_cdc.ip
#set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/msi_f2h_250_500.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/msi_ordering_0.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/cdc_msi_vector_slave_500_100.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/cdc_msi_csr_500_100.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/msi_to_gic_gen_0.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/addr_filter_0.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/dummy_writes_p1.ip
set_global_assignment -name IP_FILE ../src/ip/subsys_pcie/dummy_writes_p2.ip
