# ######################################################################## 
# Copyright (C) 2025 Altera Corporation.
# SPDX-License-Identifier: MIT
# ######################################################################## 

# TCL File Generated by Component Editor 25.1
# Tue Aug 26 06:41:51 PDT 2025
# DO NOT MODIFY


# 
# addr_filter "addr_filter" v1.0
#  2025.08.26.06:41:51
# 
# 

# 
# request TCL package from ACDS 25.1
# 
package require -exact qsys 25.1


# 
# module addr_filter
# 
set_module_property DESCRIPTION ""
set_module_property NAME addr_filter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME addr_filter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL addr_filter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file addr_filter.sv SYSTEM_VERILOG PATH addr_filter.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL addr_filter
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file addr_filter.sv SYSTEM_VERILOG PATH addr_filter.sv

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL addr_filter
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file addr_filter.sv SYSTEM_VERILOG PATH addr_filter.sv


# 
# parameters
# 
add_parameter DEVICE_FAMILY STRING "Agilex 7"
set_parameter_property DEVICE_FAMILY DEFAULT_VALUE "Agilex 7"
set_parameter_property DEVICE_FAMILY DISPLAY_NAME DEVICE_FAMILY
set_parameter_property DEVICE_FAMILY UNITS None
set_parameter_property DEVICE_FAMILY AFFECTS_GENERATION false
set_parameter_property DEVICE_FAMILY HDL_PARAMETER true
set_parameter_property DEVICE_FAMILY TRANSFORM_PARAMETER false
set_parameter_property DEVICE_FAMILY EXPORT true
add_parameter PIPELINE_MSI_GIC_START_ADDR_LSB STD_LOGIC_VECTOR 536969216 ""
set_parameter_property PIPELINE_MSI_GIC_START_ADDR_LSB DEFAULT_VALUE 536969216
set_parameter_property PIPELINE_MSI_GIC_START_ADDR_LSB DISPLAY_NAME PIPELINE_MSI_GIC_START_ADDR_LSB
set_parameter_property PIPELINE_MSI_GIC_START_ADDR_LSB WIDTH 32
set_parameter_property PIPELINE_MSI_GIC_START_ADDR_LSB UNITS None
set_parameter_property PIPELINE_MSI_GIC_START_ADDR_LSB DESCRIPTION ""
set_parameter_property PIPELINE_MSI_GIC_START_ADDR_LSB AFFECTS_GENERATION false
set_parameter_property PIPELINE_MSI_GIC_START_ADDR_LSB HDL_PARAMETER true
set_parameter_property PIPELINE_MSI_GIC_START_ADDR_LSB TRANSFORM_PARAMETER false
set_parameter_property PIPELINE_MSI_GIC_START_ADDR_LSB EXPORT true
add_parameter PIPELINE_MSI_GIC_START_ADDR_MSB STD_LOGIC_VECTOR 0 ""
set_parameter_property PIPELINE_MSI_GIC_START_ADDR_MSB DEFAULT_VALUE 0
set_parameter_property PIPELINE_MSI_GIC_START_ADDR_MSB DISPLAY_NAME PIPELINE_MSI_GIC_START_ADDR_MSB
set_parameter_property PIPELINE_MSI_GIC_START_ADDR_MSB WIDTH 32
set_parameter_property PIPELINE_MSI_GIC_START_ADDR_MSB UNITS None
set_parameter_property PIPELINE_MSI_GIC_START_ADDR_MSB DESCRIPTION ""
set_parameter_property PIPELINE_MSI_GIC_START_ADDR_MSB AFFECTS_GENERATION false
set_parameter_property PIPELINE_MSI_GIC_START_ADDR_MSB HDL_PARAMETER true
set_parameter_property PIPELINE_MSI_GIC_START_ADDR_MSB TRANSFORM_PARAMETER false
set_parameter_property PIPELINE_MSI_GIC_START_ADDR_MSB EXPORT true
add_parameter PIPELINE_MSI_GIC_END_ADDR_LSB STD_LOGIC_VECTOR 536969343 ""
set_parameter_property PIPELINE_MSI_GIC_END_ADDR_LSB DEFAULT_VALUE 536969343
set_parameter_property PIPELINE_MSI_GIC_END_ADDR_LSB DISPLAY_NAME PIPELINE_MSI_GIC_END_ADDR_LSB
set_parameter_property PIPELINE_MSI_GIC_END_ADDR_LSB WIDTH 32
set_parameter_property PIPELINE_MSI_GIC_END_ADDR_LSB UNITS None
set_parameter_property PIPELINE_MSI_GIC_END_ADDR_LSB DESCRIPTION ""
set_parameter_property PIPELINE_MSI_GIC_END_ADDR_LSB AFFECTS_GENERATION false
set_parameter_property PIPELINE_MSI_GIC_END_ADDR_LSB HDL_PARAMETER true
set_parameter_property PIPELINE_MSI_GIC_END_ADDR_LSB TRANSFORM_PARAMETER false
set_parameter_property PIPELINE_MSI_GIC_END_ADDR_LSB EXPORT true
add_parameter PIPELINE_MSI_GIC_END_ADDR_MSB STD_LOGIC_VECTOR 0
set_parameter_property PIPELINE_MSI_GIC_END_ADDR_MSB DEFAULT_VALUE 0
set_parameter_property PIPELINE_MSI_GIC_END_ADDR_MSB DISPLAY_NAME PIPELINE_MSI_GIC_END_ADDR_MSB
set_parameter_property PIPELINE_MSI_GIC_END_ADDR_MSB WIDTH 3
set_parameter_property PIPELINE_MSI_GIC_END_ADDR_MSB UNITS None
set_parameter_property PIPELINE_MSI_GIC_END_ADDR_MSB ALLOWED_RANGES 0:7
set_parameter_property PIPELINE_MSI_GIC_END_ADDR_MSB AFFECTS_GENERATION false
set_parameter_property PIPELINE_MSI_GIC_END_ADDR_MSB HDL_PARAMETER true
set_parameter_property PIPELINE_MSI_GIC_END_ADDR_MSB TRANSFORM_PARAMETER false
set_parameter_property PIPELINE_MSI_GIC_END_ADDR_MSB EXPORT true
add_parameter PIPELINE_0_START_ADDR_LSB STD_LOGIC_VECTOR 2147483648 ""
set_parameter_property PIPELINE_0_START_ADDR_LSB DEFAULT_VALUE 2147483648
set_parameter_property PIPELINE_0_START_ADDR_LSB DISPLAY_NAME PIPELINE_0_START_ADDR_LSB
set_parameter_property PIPELINE_0_START_ADDR_LSB WIDTH 32
set_parameter_property PIPELINE_0_START_ADDR_LSB UNITS None
set_parameter_property PIPELINE_0_START_ADDR_LSB DESCRIPTION ""
set_parameter_property PIPELINE_0_START_ADDR_LSB AFFECTS_GENERATION false
set_parameter_property PIPELINE_0_START_ADDR_LSB HDL_PARAMETER true
set_parameter_property PIPELINE_0_START_ADDR_LSB TRANSFORM_PARAMETER false
set_parameter_property PIPELINE_0_START_ADDR_LSB EXPORT true
add_parameter PIPELINE_0_START_ADDR_MSB STD_LOGIC_VECTOR 0 ""
set_parameter_property PIPELINE_0_START_ADDR_MSB DEFAULT_VALUE 0
set_parameter_property PIPELINE_0_START_ADDR_MSB DISPLAY_NAME PIPELINE_0_START_ADDR_MSB
set_parameter_property PIPELINE_0_START_ADDR_MSB WIDTH 32
set_parameter_property PIPELINE_0_START_ADDR_MSB UNITS None
set_parameter_property PIPELINE_0_START_ADDR_MSB DESCRIPTION ""
set_parameter_property PIPELINE_0_START_ADDR_MSB AFFECTS_GENERATION false
set_parameter_property PIPELINE_0_START_ADDR_MSB HDL_PARAMETER true
set_parameter_property PIPELINE_0_START_ADDR_MSB TRANSFORM_PARAMETER false
set_parameter_property PIPELINE_0_START_ADDR_MSB EXPORT true
add_parameter PIPELINE_0_END_ADDR_LSB STD_LOGIC_VECTOR 4294967295 ""
set_parameter_property PIPELINE_0_END_ADDR_LSB DEFAULT_VALUE 4294967295
set_parameter_property PIPELINE_0_END_ADDR_LSB DISPLAY_NAME PIPELINE_0_END_ADDR_LSB
set_parameter_property PIPELINE_0_END_ADDR_LSB WIDTH 32
set_parameter_property PIPELINE_0_END_ADDR_LSB UNITS None
set_parameter_property PIPELINE_0_END_ADDR_LSB DESCRIPTION ""
set_parameter_property PIPELINE_0_END_ADDR_LSB AFFECTS_GENERATION false
set_parameter_property PIPELINE_0_END_ADDR_LSB HDL_PARAMETER true
set_parameter_property PIPELINE_0_END_ADDR_LSB TRANSFORM_PARAMETER false
set_parameter_property PIPELINE_0_END_ADDR_LSB EXPORT true
add_parameter PIPELINE_0_END_ADDR_MSB STD_LOGIC_VECTOR 0 ""
set_parameter_property PIPELINE_0_END_ADDR_MSB DEFAULT_VALUE 0
set_parameter_property PIPELINE_0_END_ADDR_MSB DISPLAY_NAME PIPELINE_0_END_ADDR_MSB
set_parameter_property PIPELINE_0_END_ADDR_MSB WIDTH 32
set_parameter_property PIPELINE_0_END_ADDR_MSB UNITS None
set_parameter_property PIPELINE_0_END_ADDR_MSB DESCRIPTION ""
set_parameter_property PIPELINE_0_END_ADDR_MSB AFFECTS_GENERATION false
set_parameter_property PIPELINE_0_END_ADDR_MSB HDL_PARAMETER true
set_parameter_property PIPELINE_0_END_ADDR_MSB TRANSFORM_PARAMETER false
set_parameter_property PIPELINE_0_END_ADDR_MSB EXPORT true
add_parameter PIPELINE_1_START_ADDR_LSB STD_LOGIC_VECTOR 2147483648 ""
set_parameter_property PIPELINE_1_START_ADDR_LSB DEFAULT_VALUE 2147483648
set_parameter_property PIPELINE_1_START_ADDR_LSB DISPLAY_NAME PIPELINE_1_START_ADDR_LSB
set_parameter_property PIPELINE_1_START_ADDR_LSB WIDTH 32
set_parameter_property PIPELINE_1_START_ADDR_LSB UNITS None
set_parameter_property PIPELINE_1_START_ADDR_LSB DESCRIPTION ""
set_parameter_property PIPELINE_1_START_ADDR_LSB AFFECTS_GENERATION false
set_parameter_property PIPELINE_1_START_ADDR_LSB HDL_PARAMETER true
set_parameter_property PIPELINE_1_START_ADDR_LSB TRANSFORM_PARAMETER false
set_parameter_property PIPELINE_1_START_ADDR_LSB EXPORT true
add_parameter PIPELINE_1_START_ADDR_MSB STD_LOGIC_VECTOR 8 ""
set_parameter_property PIPELINE_1_START_ADDR_MSB DEFAULT_VALUE 8
set_parameter_property PIPELINE_1_START_ADDR_MSB DISPLAY_NAME PIPELINE_1_START_ADDR_MSB
set_parameter_property PIPELINE_1_START_ADDR_MSB WIDTH 32
set_parameter_property PIPELINE_1_START_ADDR_MSB UNITS None
set_parameter_property PIPELINE_1_START_ADDR_MSB DESCRIPTION ""
set_parameter_property PIPELINE_1_START_ADDR_MSB AFFECTS_GENERATION false
set_parameter_property PIPELINE_1_START_ADDR_MSB HDL_PARAMETER true
set_parameter_property PIPELINE_1_START_ADDR_MSB TRANSFORM_PARAMETER false
set_parameter_property PIPELINE_1_START_ADDR_MSB EXPORT true
add_parameter PIPELINE_1_END_ADDR_LSB STD_LOGIC_VECTOR 4294967295 ""
set_parameter_property PIPELINE_1_END_ADDR_LSB DEFAULT_VALUE 4294967295
set_parameter_property PIPELINE_1_END_ADDR_LSB DISPLAY_NAME PIPELINE_1_END_ADDR_LSB
set_parameter_property PIPELINE_1_END_ADDR_LSB WIDTH 32
set_parameter_property PIPELINE_1_END_ADDR_LSB UNITS None
set_parameter_property PIPELINE_1_END_ADDR_LSB DESCRIPTION ""
set_parameter_property PIPELINE_1_END_ADDR_LSB AFFECTS_GENERATION false
set_parameter_property PIPELINE_1_END_ADDR_LSB HDL_PARAMETER true
set_parameter_property PIPELINE_1_END_ADDR_LSB TRANSFORM_PARAMETER false
set_parameter_property PIPELINE_1_END_ADDR_LSB EXPORT true
add_parameter PIPELINE_1_END_ADDR_MSB STD_LOGIC_VECTOR 9 ""
set_parameter_property PIPELINE_1_END_ADDR_MSB DEFAULT_VALUE 9
set_parameter_property PIPELINE_1_END_ADDR_MSB DISPLAY_NAME PIPELINE_1_END_ADDR_MSB
set_parameter_property PIPELINE_1_END_ADDR_MSB WIDTH 32
set_parameter_property PIPELINE_1_END_ADDR_MSB UNITS None
set_parameter_property PIPELINE_1_END_ADDR_MSB DESCRIPTION ""
set_parameter_property PIPELINE_1_END_ADDR_MSB AFFECTS_GENERATION false
set_parameter_property PIPELINE_1_END_ADDR_MSB HDL_PARAMETER true
set_parameter_property PIPELINE_1_END_ADDR_MSB TRANSFORM_PARAMETER false
set_parameter_property PIPELINE_1_END_ADDR_MSB EXPORT true
add_parameter AXIMM_AWID_WIDTH INTEGER 8
set_parameter_property AXIMM_AWID_WIDTH DEFAULT_VALUE 8
set_parameter_property AXIMM_AWID_WIDTH DISPLAY_NAME AXIMM_AWID_WIDTH
set_parameter_property AXIMM_AWID_WIDTH UNITS None
set_parameter_property AXIMM_AWID_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXIMM_AWID_WIDTH AFFECTS_GENERATION false
set_parameter_property AXIMM_AWID_WIDTH HDL_PARAMETER true
set_parameter_property AXIMM_AWID_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AXIMM_AWID_WIDTH EXPORT true
add_parameter AXIMM_AWADDR_WIDTH INTEGER 64
set_parameter_property AXIMM_AWADDR_WIDTH DEFAULT_VALUE 64
set_parameter_property AXIMM_AWADDR_WIDTH DISPLAY_NAME AXIMM_AWADDR_WIDTH
set_parameter_property AXIMM_AWADDR_WIDTH UNITS None
set_parameter_property AXIMM_AWADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXIMM_AWADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property AXIMM_AWADDR_WIDTH HDL_PARAMETER true
set_parameter_property AXIMM_AWADDR_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AXIMM_AWADDR_WIDTH EXPORT true
add_parameter AXIMM_WDATA_WIDTH INTEGER 256
set_parameter_property AXIMM_WDATA_WIDTH DEFAULT_VALUE 256
set_parameter_property AXIMM_WDATA_WIDTH DISPLAY_NAME AXIMM_WDATA_WIDTH
set_parameter_property AXIMM_WDATA_WIDTH UNITS None
set_parameter_property AXIMM_WDATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXIMM_WDATA_WIDTH AFFECTS_GENERATION false
set_parameter_property AXIMM_WDATA_WIDTH HDL_PARAMETER true
set_parameter_property AXIMM_WDATA_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AXIMM_WDATA_WIDTH EXPORT true
add_parameter AXIMM_BID_WIDTH INTEGER 8
set_parameter_property AXIMM_BID_WIDTH DEFAULT_VALUE 8
set_parameter_property AXIMM_BID_WIDTH DISPLAY_NAME AXIMM_BID_WIDTH
set_parameter_property AXIMM_BID_WIDTH UNITS None
set_parameter_property AXIMM_BID_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXIMM_BID_WIDTH AFFECTS_GENERATION false
set_parameter_property AXIMM_BID_WIDTH HDL_PARAMETER true
set_parameter_property AXIMM_BID_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AXIMM_BID_WIDTH EXPORT true
add_parameter AXIMM_ARID_WIDTH INTEGER 8
set_parameter_property AXIMM_ARID_WIDTH DEFAULT_VALUE 8
set_parameter_property AXIMM_ARID_WIDTH DISPLAY_NAME AXIMM_ARID_WIDTH
set_parameter_property AXIMM_ARID_WIDTH UNITS None
set_parameter_property AXIMM_ARID_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXIMM_ARID_WIDTH AFFECTS_GENERATION false
set_parameter_property AXIMM_ARID_WIDTH HDL_PARAMETER true
set_parameter_property AXIMM_ARID_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AXIMM_ARID_WIDTH EXPORT true
add_parameter AXIMM_ARADDR_WIDTH INTEGER 64
set_parameter_property AXIMM_ARADDR_WIDTH DEFAULT_VALUE 64
set_parameter_property AXIMM_ARADDR_WIDTH DISPLAY_NAME AXIMM_ARADDR_WIDTH
set_parameter_property AXIMM_ARADDR_WIDTH UNITS None
set_parameter_property AXIMM_ARADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXIMM_ARADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property AXIMM_ARADDR_WIDTH HDL_PARAMETER true
set_parameter_property AXIMM_ARADDR_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AXIMM_ARADDR_WIDTH EXPORT true
add_parameter AXIMM_RID_WIDTH INTEGER 8
set_parameter_property AXIMM_RID_WIDTH DEFAULT_VALUE 8
set_parameter_property AXIMM_RID_WIDTH DISPLAY_NAME AXIMM_RID_WIDTH
set_parameter_property AXIMM_RID_WIDTH UNITS None
set_parameter_property AXIMM_RID_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXIMM_RID_WIDTH AFFECTS_GENERATION false
set_parameter_property AXIMM_RID_WIDTH HDL_PARAMETER true
set_parameter_property AXIMM_RID_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AXIMM_RID_WIDTH EXPORT true
add_parameter AXIMM_RDATA_WIDTH INTEGER 256
set_parameter_property AXIMM_RDATA_WIDTH DEFAULT_VALUE 256
set_parameter_property AXIMM_RDATA_WIDTH DISPLAY_NAME AXIMM_RDATA_WIDTH
set_parameter_property AXIMM_RDATA_WIDTH UNITS None
set_parameter_property AXIMM_RDATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXIMM_RDATA_WIDTH AFFECTS_GENERATION false
set_parameter_property AXIMM_RDATA_WIDTH HDL_PARAMETER true
set_parameter_property AXIMM_RDATA_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AXIMM_RDATA_WIDTH EXPORT true


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""
set_interface_property clk IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clk SV_INTERFACE_TYPE ""
set_interface_property clk SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clk clk clk Input 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""
set_interface_property rst IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property rst SV_INTERFACE_TYPE ""
set_interface_property rst SV_INTERFACE_MODPORT_TYPE ""

add_interface_port rst rst reset Input 1


# 
# connection point egr_axi
# 
add_interface egr_axi axi4 start
set_interface_property egr_axi associatedClock clk
set_interface_property egr_axi associatedReset rst
set_interface_property egr_axi wakeupSignals false
set_interface_property egr_axi uniqueIdSupport false
set_interface_property egr_axi poison false
set_interface_property egr_axi traceSignals false
set_interface_property egr_axi isTranslator false
set_interface_property egr_axi dataCheck false
set_interface_property egr_axi addressCheck false
set_interface_property egr_axi securityAttribute false
set_interface_property egr_axi userData false
set_interface_property egr_axi readIssuingCapability 16
set_interface_property egr_axi writeIssuingCapability 16
set_interface_property egr_axi combinedIssuingCapability 16
set_interface_property egr_axi enableConcurrentSubordinateAccess 0
set_interface_property egr_axi noRepeatedIdsBetweenSubordinates 0
set_interface_property egr_axi issuesINCRBursts true
set_interface_property egr_axi issuesWRAPBursts true
set_interface_property egr_axi issuesFIXEDBursts true
set_interface_property egr_axi ENABLED true
set_interface_property egr_axi EXPORT_OF ""
set_interface_property egr_axi PORT_NAME_MAP ""
set_interface_property egr_axi CMSIS_SVD_VARIABLES ""
set_interface_property egr_axi SVD_ADDRESS_GROUP ""
set_interface_property egr_axi IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property egr_axi SV_INTERFACE_TYPE ""
set_interface_property egr_axi SV_INTERFACE_MODPORT_TYPE ""

add_interface_port egr_axi egr_axi_awid awid Output "((AXIMM_AWID_WIDTH - 1)) - (0) + 1"
add_interface_port egr_axi egr_axi_awaddr awaddr Output "((AXIMM_AWADDR_WIDTH - 1)) - (0) + 1"
add_interface_port egr_axi egr_axi_awlen awlen Output 8
add_interface_port egr_axi egr_axi_awsize awsize Output 3
add_interface_port egr_axi egr_axi_awburst awburst Output 2
add_interface_port egr_axi egr_axi_awlock awlock Output 1
set_port_property egr_axi_awlock VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port egr_axi egr_axi_awcache awcache Output 4
add_interface_port egr_axi egr_axi_awprot awprot Output 3
add_interface_port egr_axi egr_axi_awvalid awvalid Output 1
add_interface_port egr_axi egr_axi_awready awready Input 1
add_interface_port egr_axi egr_axi_wdata wdata Output "((AXIMM_WDATA_WIDTH - 1)) - (0) + 1"
add_interface_port egr_axi egr_axi_wstrb wstrb Output "(((AXIMM_WDATA_WIDTH / 8) - 1)) - (0) + 1"
add_interface_port egr_axi egr_axi_wlast wlast Output 1
add_interface_port egr_axi egr_axi_wvalid wvalid Output 1
add_interface_port egr_axi egr_axi_wready wready Input 1
add_interface_port egr_axi egr_axi_bid bid Input "((AXIMM_BID_WIDTH - 1)) - (0) + 1"
add_interface_port egr_axi egr_axi_bresp bresp Input 2
add_interface_port egr_axi egr_axi_bvalid bvalid Input 1
add_interface_port egr_axi egr_axi_bready bready Output 1
add_interface_port egr_axi egr_axi_arid arid Output "((AXIMM_ARID_WIDTH - 1)) - (0) + 1"
add_interface_port egr_axi egr_axi_araddr araddr Output "((AXIMM_ARADDR_WIDTH - 1)) - (0) + 1"
add_interface_port egr_axi egr_axi_arlen arlen Output 8
add_interface_port egr_axi egr_axi_arsize arsize Output 3
add_interface_port egr_axi egr_axi_arburst arburst Output 2
add_interface_port egr_axi egr_axi_arlock arlock Output 1
set_port_property egr_axi_arlock VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port egr_axi egr_axi_arcache arcache Output 4
add_interface_port egr_axi egr_axi_arprot arprot Output 3
add_interface_port egr_axi egr_axi_arvalid arvalid Output 1
add_interface_port egr_axi egr_axi_arready arready Input 1
add_interface_port egr_axi egr_axi_rid rid Input "((AXIMM_RID_WIDTH - 1)) - (0) + 1"
add_interface_port egr_axi egr_axi_rdata rdata Input "((AXIMM_RDATA_WIDTH - 1)) - (0) + 1"
add_interface_port egr_axi egr_axi_rresp rresp Input 2
add_interface_port egr_axi egr_axi_rlast rlast Input 1
add_interface_port egr_axi egr_axi_rvalid rvalid Input 1
add_interface_port egr_axi egr_axi_rready rready Output 1


# 
# connection point igr_axi
# 
add_interface igr_axi axi4 end
set_interface_property igr_axi associatedClock clk
set_interface_property igr_axi associatedReset rst
set_interface_property igr_axi wakeupSignals false
set_interface_property igr_axi uniqueIdSupport false
set_interface_property igr_axi poison false
set_interface_property igr_axi traceSignals false
set_interface_property igr_axi isTranslator false
set_interface_property igr_axi dataCheck false
set_interface_property igr_axi addressCheck false
set_interface_property igr_axi securityAttribute false
set_interface_property igr_axi userData false
set_interface_property igr_axi readAcceptanceCapability 16
set_interface_property igr_axi writeAcceptanceCapability 16
set_interface_property igr_axi combinedAcceptanceCapability 16
set_interface_property igr_axi readDataReorderingDepth 1
set_interface_property igr_axi bridgesToMaster ""
set_interface_property igr_axi dfhFeatureGuid 0
set_interface_property igr_axi dfhGroupId 0
set_interface_property igr_axi dfhParameterId ""
set_interface_property igr_axi dfhParameterName ""
set_interface_property igr_axi dfhParameterVersion ""
set_interface_property igr_axi dfhParameterData ""
set_interface_property igr_axi dfhParameterDataLength ""
set_interface_property igr_axi dfhFeatureMajorVersion 0
set_interface_property igr_axi dfhFeatureMinorVersion 0
set_interface_property igr_axi dfhFeatureId 35
set_interface_property igr_axi dfhFeatureType 3
set_interface_property igr_axi ENABLED true
set_interface_property igr_axi EXPORT_OF ""
set_interface_property igr_axi PORT_NAME_MAP ""
set_interface_property igr_axi CMSIS_SVD_VARIABLES ""
set_interface_property igr_axi SVD_ADDRESS_GROUP ""
set_interface_property igr_axi IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property igr_axi SV_INTERFACE_TYPE ""
set_interface_property igr_axi SV_INTERFACE_MODPORT_TYPE ""

add_interface_port igr_axi igr_axi_awid awid Input "((AXIMM_AWID_WIDTH - 1)) - (0) + 1"
add_interface_port igr_axi igr_axi_awaddr awaddr Input "((AXIMM_AWADDR_WIDTH - 1)) - (0) + 1"
add_interface_port igr_axi igr_axi_awlen awlen Input 8
add_interface_port igr_axi igr_axi_awsize awsize Input 3
add_interface_port igr_axi igr_axi_awburst awburst Input 2
add_interface_port igr_axi igr_axi_awlock awlock Input 1
set_port_property igr_axi_awlock VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port igr_axi igr_axi_awcache awcache Input 4
add_interface_port igr_axi igr_axi_awprot awprot Input 3
add_interface_port igr_axi igr_axi_awvalid awvalid Input 1
add_interface_port igr_axi igr_axi_awready awready Output 1
add_interface_port igr_axi igr_axi_wdata wdata Input "((AXIMM_WDATA_WIDTH - 1)) - (0) + 1"
add_interface_port igr_axi igr_axi_wstrb wstrb Input "(((AXIMM_WDATA_WIDTH / 8) - 1)) - (0) + 1"
add_interface_port igr_axi igr_axi_wlast wlast Input 1
add_interface_port igr_axi igr_axi_wvalid wvalid Input 1
add_interface_port igr_axi igr_axi_wready wready Output 1
add_interface_port igr_axi igr_axi_bid bid Output "((AXIMM_BID_WIDTH - 1)) - (0) + 1"
add_interface_port igr_axi igr_axi_bresp bresp Output 2
add_interface_port igr_axi igr_axi_bvalid bvalid Output 1
add_interface_port igr_axi igr_axi_bready bready Input 1
add_interface_port igr_axi igr_axi_arid arid Input "((AXIMM_ARID_WIDTH - 1)) - (0) + 1"
add_interface_port igr_axi igr_axi_araddr araddr Input "((AXIMM_ARADDR_WIDTH - 1)) - (0) + 1"
add_interface_port igr_axi igr_axi_arlen arlen Input 8
add_interface_port igr_axi igr_axi_arsize arsize Input 3
add_interface_port igr_axi igr_axi_arburst arburst Input 2
add_interface_port igr_axi igr_axi_arlock arlock Input 1
set_port_property igr_axi_arlock VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port igr_axi igr_axi_arcache arcache Input 4
add_interface_port igr_axi igr_axi_arprot arprot Input 3
add_interface_port igr_axi igr_axi_arvalid arvalid Input 1
add_interface_port igr_axi igr_axi_arready arready Output 1
add_interface_port igr_axi igr_axi_rid rid Output "((AXIMM_RID_WIDTH - 1)) - (0) + 1"
add_interface_port igr_axi igr_axi_rdata rdata Output "((AXIMM_RDATA_WIDTH - 1)) - (0) + 1"
add_interface_port igr_axi igr_axi_rresp rresp Output 2
add_interface_port igr_axi igr_axi_rlast rlast Output 1
add_interface_port igr_axi igr_axi_rvalid rvalid Output 1
add_interface_port igr_axi igr_axi_rready rready Input 1


# 
# connection point egr_msi_axi
# 
add_interface egr_msi_axi axi4 start
set_interface_property egr_msi_axi associatedClock clk
set_interface_property egr_msi_axi associatedReset rst
set_interface_property egr_msi_axi wakeupSignals false
set_interface_property egr_msi_axi uniqueIdSupport false
set_interface_property egr_msi_axi poison false
set_interface_property egr_msi_axi traceSignals false
set_interface_property egr_msi_axi isTranslator false
set_interface_property egr_msi_axi dataCheck false
set_interface_property egr_msi_axi addressCheck false
set_interface_property egr_msi_axi securityAttribute false
set_interface_property egr_msi_axi userData false
set_interface_property egr_msi_axi readIssuingCapability 1
set_interface_property egr_msi_axi writeIssuingCapability 1
set_interface_property egr_msi_axi combinedIssuingCapability 1
set_interface_property egr_msi_axi enableConcurrentSubordinateAccess 0
set_interface_property egr_msi_axi noRepeatedIdsBetweenSubordinates 0
set_interface_property egr_msi_axi issuesINCRBursts true
set_interface_property egr_msi_axi issuesWRAPBursts true
set_interface_property egr_msi_axi issuesFIXEDBursts true
set_interface_property egr_msi_axi ENABLED true
set_interface_property egr_msi_axi EXPORT_OF ""
set_interface_property egr_msi_axi PORT_NAME_MAP ""
set_interface_property egr_msi_axi CMSIS_SVD_VARIABLES ""
set_interface_property egr_msi_axi SVD_ADDRESS_GROUP ""
set_interface_property egr_msi_axi IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property egr_msi_axi SV_INTERFACE_TYPE ""
set_interface_property egr_msi_axi SV_INTERFACE_MODPORT_TYPE ""

add_interface_port egr_msi_axi egr_msi_axi_awid awid Output "((AXIMM_AWID_WIDTH - 1)) - (0) + 1"
add_interface_port egr_msi_axi egr_msi_axi_awaddr awaddr Output "((AXIMM_AWADDR_WIDTH - 1)) - (0) + 1"
add_interface_port egr_msi_axi egr_msi_axi_awlen awlen Output 8
add_interface_port egr_msi_axi egr_msi_axi_awsize awsize Output 3
add_interface_port egr_msi_axi egr_msi_axi_awburst awburst Output 2
add_interface_port egr_msi_axi egr_msi_axi_awlock awlock Output 1
set_port_property egr_msi_axi_awlock VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port egr_msi_axi egr_msi_axi_awcache awcache Output 4
add_interface_port egr_msi_axi egr_msi_axi_awprot awprot Output 3
add_interface_port egr_msi_axi egr_msi_axi_awvalid awvalid Output 1
add_interface_port egr_msi_axi egr_msi_axi_awready awready Input 1
add_interface_port egr_msi_axi egr_msi_axi_wdata wdata Output "((AXIMM_WDATA_WIDTH - 1)) - (0) + 1"
add_interface_port egr_msi_axi egr_msi_axi_wstrb wstrb Output "(((AXIMM_WDATA_WIDTH / 8) - 1)) - (0) + 1"
add_interface_port egr_msi_axi egr_msi_axi_wlast wlast Output 1
add_interface_port egr_msi_axi egr_msi_axi_wvalid wvalid Output 1
add_interface_port egr_msi_axi egr_msi_axi_wready wready Input 1
add_interface_port egr_msi_axi egr_msi_axi_bid bid Input "((AXIMM_BID_WIDTH - 1)) - (0) + 1"
add_interface_port egr_msi_axi egr_msi_axi_bresp bresp Input 2
add_interface_port egr_msi_axi egr_msi_axi_bvalid bvalid Input 1
add_interface_port egr_msi_axi egr_msi_axi_bready bready Output 1
add_interface_port egr_msi_axi egr_msi_axi_arid arid Output "((AXIMM_ARID_WIDTH - 1)) - (0) + 1"
add_interface_port egr_msi_axi egr_msi_axi_araddr araddr Output "((AXIMM_ARADDR_WIDTH - 1)) - (0) + 1"
add_interface_port egr_msi_axi egr_msi_axi_arlen arlen Output 8
add_interface_port egr_msi_axi egr_msi_axi_arsize arsize Output 3
add_interface_port egr_msi_axi egr_msi_axi_arburst arburst Output 2
add_interface_port egr_msi_axi egr_msi_axi_arlock arlock Output 1
set_port_property egr_msi_axi_arlock VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port egr_msi_axi egr_msi_axi_arcache arcache Output 4
add_interface_port egr_msi_axi egr_msi_axi_arprot arprot Output 3
add_interface_port egr_msi_axi egr_msi_axi_arvalid arvalid Output 1
add_interface_port egr_msi_axi egr_msi_axi_arready arready Input 1
add_interface_port egr_msi_axi egr_msi_axi_rid rid Input "((AXIMM_RID_WIDTH - 1)) - (0) + 1"
add_interface_port egr_msi_axi egr_msi_axi_rdata rdata Input "((AXIMM_RDATA_WIDTH - 1)) - (0) + 1"
add_interface_port egr_msi_axi egr_msi_axi_rresp rresp Input 2
add_interface_port egr_msi_axi egr_msi_axi_rlast rlast Input 1
add_interface_port egr_msi_axi egr_msi_axi_rvalid rvalid Input 1
add_interface_port egr_msi_axi egr_msi_axi_rready rready Output 1

