# ######################################################################## 
# Copyright (C) 2025 Altera Corporation.
# SPDX-License-Identifier: MIT
# ######################################################################## 
#
# TCL File Generated by Component Editor 25.1
# Sun Sep 07 23:00:38 PDT 2025
# DO NOT MODIFY


# 
# msi_ordering "msi_ordering" v1.0
#  2025.09.08.23:15:10
# 
# 

# 
# request TCL package from ACDS 25.1.1
# 
package require -exact qsys 25.1.1


# 
# module msi_ordering
# 
set_module_property DESCRIPTION ""
set_module_property NAME msi_ordering
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME msi_ordering
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL msi_ordering
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file msi_ordering.sv SYSTEM_VERILOG PATH msi_ordering.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL msi_ordering
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file msi_ordering.sv SYSTEM_VERILOG PATH msi_ordering.sv

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL msi_ordering
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file msi_ordering.sv SYSTEM_VERILOG PATH msi_ordering.sv


# 
# parameters
# 
add_parameter DEVICE_FAMILY STRING "Agilex 7"
set_parameter_property DEVICE_FAMILY DEFAULT_VALUE "Agilex 7"
set_parameter_property DEVICE_FAMILY DISPLAY_NAME DEVICE_FAMILY
set_parameter_property DEVICE_FAMILY UNITS None
set_parameter_property DEVICE_FAMILY AFFECTS_GENERATION false
set_parameter_property DEVICE_FAMILY HDL_PARAMETER true
set_parameter_property DEVICE_FAMILY TRANSFORM_PARAMETER false
set_parameter_property DEVICE_FAMILY EXPORT true
set_parameter_property DEVICE_FAMILY READ_ONLY false
add_parameter ADDR_WIDTH INTEGER 5
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 5
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
set_parameter_property ADDR_WIDTH TRANSFORM_PARAMETER false
set_parameter_property ADDR_WIDTH EXPORT true
set_parameter_property ADDR_WIDTH READ_ONLY false
add_parameter DATA_WIDTH INTEGER 32 ""
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH DESCRIPTION ""
set_parameter_property DATA_WIDTH AFFECTS_GENERATION false
set_parameter_property DATA_WIDTH HDL_PARAMETER true
set_parameter_property DATA_WIDTH TRANSFORM_PARAMETER false
set_parameter_property DATA_WIDTH EXPORT true
set_parameter_property DATA_WIDTH READ_ONLY false
add_parameter NUM_VECTORS INTEGER 32
set_parameter_property NUM_VECTORS DEFAULT_VALUE 32
set_parameter_property NUM_VECTORS DISPLAY_NAME NUM_VECTORS
set_parameter_property NUM_VECTORS UNITS None
set_parameter_property NUM_VECTORS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NUM_VECTORS AFFECTS_GENERATION false
set_parameter_property NUM_VECTORS HDL_PARAMETER true
set_parameter_property NUM_VECTORS TRANSFORM_PARAMETER false
set_parameter_property NUM_VECTORS EXPORT true
set_parameter_property NUM_VECTORS READ_ONLY false
add_parameter MAX_OUTSTANDING_MSI INTEGER 16 ""
set_parameter_property MAX_OUTSTANDING_MSI DEFAULT_VALUE 16
set_parameter_property MAX_OUTSTANDING_MSI DISPLAY_NAME MAX_OUTSTANDING_MSI
set_parameter_property MAX_OUTSTANDING_MSI UNITS None
set_parameter_property MAX_OUTSTANDING_MSI ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MAX_OUTSTANDING_MSI DESCRIPTION ""
set_parameter_property MAX_OUTSTANDING_MSI AFFECTS_GENERATION false
set_parameter_property MAX_OUTSTANDING_MSI HDL_PARAMETER true
set_parameter_property MAX_OUTSTANDING_MSI TRANSFORM_PARAMETER false
set_parameter_property MAX_OUTSTANDING_MSI EXPORT true
set_parameter_property MAX_OUTSTANDING_MSI READ_ONLY false
add_parameter AXIMM_AWID_WIDTH INTEGER 1
set_parameter_property AXIMM_AWID_WIDTH DEFAULT_VALUE 1
set_parameter_property AXIMM_AWID_WIDTH DISPLAY_NAME AXIMM_AWID_WIDTH
set_parameter_property AXIMM_AWID_WIDTH UNITS None
set_parameter_property AXIMM_AWID_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXIMM_AWID_WIDTH AFFECTS_GENERATION false
set_parameter_property AXIMM_AWID_WIDTH HDL_PARAMETER true
set_parameter_property AXIMM_AWID_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AXIMM_AWID_WIDTH EXPORT true
set_parameter_property AXIMM_AWID_WIDTH READ_ONLY false
add_parameter AXIMM_AWADDR_WIDTH INTEGER 36
set_parameter_property AXIMM_AWADDR_WIDTH DEFAULT_VALUE 36
set_parameter_property AXIMM_AWADDR_WIDTH DISPLAY_NAME AXIMM_AWADDR_WIDTH
set_parameter_property AXIMM_AWADDR_WIDTH UNITS None
set_parameter_property AXIMM_AWADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXIMM_AWADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property AXIMM_AWADDR_WIDTH HDL_PARAMETER true
set_parameter_property AXIMM_AWADDR_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AXIMM_AWADDR_WIDTH EXPORT true
set_parameter_property AXIMM_AWADDR_WIDTH READ_ONLY false
add_parameter AXIMM_WDATA_WIDTH INTEGER 256
set_parameter_property AXIMM_WDATA_WIDTH DEFAULT_VALUE 256
set_parameter_property AXIMM_WDATA_WIDTH DISPLAY_NAME AXIMM_WDATA_WIDTH
set_parameter_property AXIMM_WDATA_WIDTH UNITS None
set_parameter_property AXIMM_WDATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXIMM_WDATA_WIDTH AFFECTS_GENERATION false
set_parameter_property AXIMM_WDATA_WIDTH HDL_PARAMETER true
set_parameter_property AXIMM_WDATA_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AXIMM_WDATA_WIDTH EXPORT true
set_parameter_property AXIMM_WDATA_WIDTH READ_ONLY false
add_parameter AXIMM_BID_WIDTH INTEGER 1
set_parameter_property AXIMM_BID_WIDTH DEFAULT_VALUE 1
set_parameter_property AXIMM_BID_WIDTH DISPLAY_NAME AXIMM_BID_WIDTH
set_parameter_property AXIMM_BID_WIDTH UNITS None
set_parameter_property AXIMM_BID_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXIMM_BID_WIDTH AFFECTS_GENERATION false
set_parameter_property AXIMM_BID_WIDTH HDL_PARAMETER true
set_parameter_property AXIMM_BID_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AXIMM_BID_WIDTH EXPORT true
set_parameter_property AXIMM_BID_WIDTH READ_ONLY false
add_parameter AXIMM_ARID_WIDTH INTEGER 1
set_parameter_property AXIMM_ARID_WIDTH DEFAULT_VALUE 1
set_parameter_property AXIMM_ARID_WIDTH DISPLAY_NAME AXIMM_ARID_WIDTH
set_parameter_property AXIMM_ARID_WIDTH UNITS None
set_parameter_property AXIMM_ARID_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXIMM_ARID_WIDTH AFFECTS_GENERATION false
set_parameter_property AXIMM_ARID_WIDTH HDL_PARAMETER true
set_parameter_property AXIMM_ARID_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AXIMM_ARID_WIDTH EXPORT true
set_parameter_property AXIMM_ARID_WIDTH READ_ONLY false
add_parameter AXIMM_ARADDR_WIDTH INTEGER 36
set_parameter_property AXIMM_ARADDR_WIDTH DEFAULT_VALUE 36
set_parameter_property AXIMM_ARADDR_WIDTH DISPLAY_NAME AXIMM_ARADDR_WIDTH
set_parameter_property AXIMM_ARADDR_WIDTH UNITS None
set_parameter_property AXIMM_ARADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXIMM_ARADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property AXIMM_ARADDR_WIDTH HDL_PARAMETER true
set_parameter_property AXIMM_ARADDR_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AXIMM_ARADDR_WIDTH EXPORT true
set_parameter_property AXIMM_ARADDR_WIDTH READ_ONLY false
add_parameter AXIMM_RID_WIDTH INTEGER 1
set_parameter_property AXIMM_RID_WIDTH DEFAULT_VALUE 1
set_parameter_property AXIMM_RID_WIDTH DISPLAY_NAME AXIMM_RID_WIDTH
set_parameter_property AXIMM_RID_WIDTH UNITS None
set_parameter_property AXIMM_RID_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXIMM_RID_WIDTH AFFECTS_GENERATION false
set_parameter_property AXIMM_RID_WIDTH HDL_PARAMETER true
set_parameter_property AXIMM_RID_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AXIMM_RID_WIDTH EXPORT true
set_parameter_property AXIMM_RID_WIDTH READ_ONLY false
add_parameter AXIMM_RDATA_WIDTH INTEGER 256
set_parameter_property AXIMM_RDATA_WIDTH DEFAULT_VALUE 256
set_parameter_property AXIMM_RDATA_WIDTH DISPLAY_NAME AXIMM_RDATA_WIDTH
set_parameter_property AXIMM_RDATA_WIDTH UNITS None
set_parameter_property AXIMM_RDATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXIMM_RDATA_WIDTH AFFECTS_GENERATION false
set_parameter_property AXIMM_RDATA_WIDTH HDL_PARAMETER true
set_parameter_property AXIMM_RDATA_WIDTH TRANSFORM_PARAMETER false
set_parameter_property AXIMM_RDATA_WIDTH EXPORT true
set_parameter_property AXIMM_RDATA_WIDTH READ_ONLY false


# 
# display items
# 


# 
# connection point igr_avmm
# 
add_interface igr_avmm avalon end
set_interface_property igr_avmm addressGroup 0
set_interface_property igr_avmm addressUnits WORDS
set_interface_property igr_avmm associatedClock clk
set_interface_property igr_avmm associatedReset rst
set_interface_property igr_avmm bitsPerSymbol 8
set_interface_property igr_avmm bridgedAddressOffset 0
set_interface_property igr_avmm bridgesToMaster ""
set_interface_property igr_avmm burstOnBurstBoundariesOnly false
set_interface_property igr_avmm burstcountUnits WORDS
set_interface_property igr_avmm explicitAddressSpan 0
set_interface_property igr_avmm holdTime 0
set_interface_property igr_avmm linewrapBursts false
set_interface_property igr_avmm maximumPendingReadTransactions 0
set_interface_property igr_avmm maximumPendingWriteTransactions 0
set_interface_property igr_avmm minimumResponseLatency 1
set_interface_property igr_avmm readLatency 0
set_interface_property igr_avmm readWaitTime 1
set_interface_property igr_avmm setupTime 0
set_interface_property igr_avmm timingUnits Cycles
set_interface_property igr_avmm transparentBridge false
set_interface_property igr_avmm waitrequestAllowance 0
set_interface_property igr_avmm writeWaitTime 0
set_interface_property igr_avmm dfhFeatureGuid 0
set_interface_property igr_avmm dfhGroupId 0
set_interface_property igr_avmm dfhParameterId ""
set_interface_property igr_avmm dfhParameterName ""
set_interface_property igr_avmm dfhParameterVersion ""
set_interface_property igr_avmm dfhParameterData ""
set_interface_property igr_avmm dfhParameterDataLength ""
set_interface_property igr_avmm dfhFeatureMajorVersion 0
set_interface_property igr_avmm dfhFeatureMinorVersion 0
set_interface_property igr_avmm dfhFeatureId 35
set_interface_property igr_avmm dfhFeatureType 3
set_interface_property igr_avmm ENABLED true
set_interface_property igr_avmm EXPORT_OF ""
set_interface_property igr_avmm PORT_NAME_MAP ""
set_interface_property igr_avmm CMSIS_SVD_VARIABLES ""
set_interface_property igr_avmm SVD_ADDRESS_GROUP ""
set_interface_property igr_avmm IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property igr_avmm SV_INTERFACE_TYPE ""
set_interface_property igr_avmm SV_INTERFACE_MODPORT_TYPE ""

add_interface_port igr_avmm igr_avmm_byteenable byteenable Input "(((DATA_WIDTH / 8) - 1)) - (0) + 1"
add_interface_port igr_avmm igr_avmm_wr write Input 1
add_interface_port igr_avmm igr_avmm_rd read Input 1
add_interface_port igr_avmm igr_avmm_addr address Input "((ADDR_WIDTH - 1)) - (0) + 1"
add_interface_port igr_avmm igr_avmm_wrdata writedata Input "((DATA_WIDTH - 1)) - (0) + 1"
add_interface_port igr_avmm igr_avmm_rddata readdata Output "((DATA_WIDTH - 1)) - (0) + 1"
add_interface_port igr_avmm igr_avmm_waitreq waitrequest Output 1
set_interface_assignment igr_avmm embeddedsw.configuration.isFlash 0
set_interface_assignment igr_avmm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment igr_avmm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment igr_avmm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point egr_avmm
# 
add_interface egr_avmm avalon start
set_interface_property egr_avmm addressGroup 0
set_interface_property egr_avmm addressUnits WORDS
set_interface_property egr_avmm associatedClock clk
set_interface_property egr_avmm associatedReset rst
set_interface_property egr_avmm bitsPerSymbol 8
set_interface_property egr_avmm burstOnBurstBoundariesOnly false
set_interface_property egr_avmm burstcountUnits WORDS
set_interface_property egr_avmm doStreamReads false
set_interface_property egr_avmm doStreamWrites false
set_interface_property egr_avmm holdTime 0
set_interface_property egr_avmm linewrapBursts false
set_interface_property egr_avmm maximumPendingReadTransactions 0
set_interface_property egr_avmm maximumPendingWriteTransactions 0
set_interface_property egr_avmm minimumResponseLatency 1
set_interface_property egr_avmm readLatency 0
set_interface_property egr_avmm readWaitTime 1
set_interface_property egr_avmm setupTime 0
set_interface_property egr_avmm timingUnits Cycles
set_interface_property egr_avmm waitrequestAllowance 0
set_interface_property egr_avmm waitrequestTimeout 1024
set_interface_property egr_avmm writeWaitTime 0
set_interface_property egr_avmm enableConcurrentSubordinateAccess 0
set_interface_property egr_avmm optimizedReadsWithBE 0
set_interface_property egr_avmm ENABLED true
set_interface_property egr_avmm EXPORT_OF ""
set_interface_property egr_avmm PORT_NAME_MAP ""
set_interface_property egr_avmm CMSIS_SVD_VARIABLES ""
set_interface_property egr_avmm SVD_ADDRESS_GROUP ""
set_interface_property egr_avmm IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property egr_avmm SV_INTERFACE_TYPE ""
set_interface_property egr_avmm SV_INTERFACE_MODPORT_TYPE ""

add_interface_port egr_avmm egr_avmm_wr write Output 1
add_interface_port egr_avmm egr_avmm_rd read Output 1
add_interface_port egr_avmm egr_avmm_addr address Output "((ADDR_WIDTH - 1)) - (0) + 1"
add_interface_port egr_avmm egr_avmm_wrdata writedata Output "((DATA_WIDTH - 1)) - (0) + 1"
add_interface_port egr_avmm egr_avmm_byteenable byteenable Output "(((DATA_WIDTH / 8) - 1)) - (0) + 1"
add_interface_port egr_avmm egr_avmm_burstcount burstcount Output 1
add_interface_port egr_avmm egr_avmm_rddata readdata Input "((DATA_WIDTH - 1)) - (0) + 1"
add_interface_port egr_avmm egr_avmm_waitreq waitrequest Input 1
add_interface_port egr_avmm egr_avmm_rddata_vld readdatavalid Input 1


# 
# connection point f2h_avmm
# 
add_interface f2h_avmm avalon start
set_interface_property f2h_avmm addressGroup 0
set_interface_property f2h_avmm addressUnits SYMBOLS
set_interface_property f2h_avmm associatedClock clk
set_interface_property f2h_avmm associatedReset rst
set_interface_property f2h_avmm bitsPerSymbol 8
set_interface_property f2h_avmm burstOnBurstBoundariesOnly false
set_interface_property f2h_avmm burstcountUnits WORDS
set_interface_property f2h_avmm doStreamReads false
set_interface_property f2h_avmm doStreamWrites false
set_interface_property f2h_avmm holdTime 0
set_interface_property f2h_avmm linewrapBursts false
set_interface_property f2h_avmm maximumPendingReadTransactions 0
set_interface_property f2h_avmm maximumPendingWriteTransactions 0
set_interface_property f2h_avmm minimumResponseLatency 1
set_interface_property f2h_avmm readLatency 0
set_interface_property f2h_avmm readWaitTime 1
set_interface_property f2h_avmm setupTime 0
set_interface_property f2h_avmm timingUnits Cycles
set_interface_property f2h_avmm waitrequestAllowance 0
set_interface_property f2h_avmm waitrequestTimeout 1024
set_interface_property f2h_avmm writeWaitTime 0
set_interface_property f2h_avmm enableConcurrentSubordinateAccess 0
set_interface_property f2h_avmm optimizedReadsWithBE 0
set_interface_property f2h_avmm ENABLED true
set_interface_property f2h_avmm EXPORT_OF ""
set_interface_property f2h_avmm PORT_NAME_MAP ""
set_interface_property f2h_avmm CMSIS_SVD_VARIABLES ""
set_interface_property f2h_avmm SVD_ADDRESS_GROUP ""
set_interface_property f2h_avmm IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property f2h_avmm SV_INTERFACE_TYPE ""
set_interface_property f2h_avmm SV_INTERFACE_MODPORT_TYPE ""

add_interface_port f2h_avmm f2h_avmm_wr write Output 1
add_interface_port f2h_avmm f2h_avmm_rd read Output 1
add_interface_port f2h_avmm f2h_avmm_addr address Output "((AXIMM_AWADDR_WIDTH - 1)) - (0) + 1"
add_interface_port f2h_avmm f2h_avmm_wrdata writedata Output "((AXIMM_WDATA_WIDTH - 1)) - (0) + 1"
add_interface_port f2h_avmm f2h_avmm_byteenable byteenable Output "(((AXIMM_WDATA_WIDTH / 8) - 1)) - (0) + 1"
add_interface_port f2h_avmm f2h_avmm_burstcount burstcount Output 1
add_interface_port f2h_avmm f2h_avmm_rddata readdata Input "((AXIMM_RDATA_WIDTH - 1)) - (0) + 1"
add_interface_port f2h_avmm f2h_avmm_waitreq waitrequest Input 1
add_interface_port f2h_avmm f2h_avmm_rddata_vld readdatavalid Input 1


# 
# connection point egr_axi
# 
add_interface egr_axi axi4 start
set_interface_property egr_axi associatedClock clk
set_interface_property egr_axi associatedReset rst
set_interface_property egr_axi wakeupSignals false
set_interface_property egr_axi uniqueIdSupport false
set_interface_property egr_axi poison false
set_interface_property egr_axi traceSignals false
set_interface_property egr_axi isTranslator false
set_interface_property egr_axi dataCheck false
set_interface_property egr_axi addressCheck false
set_interface_property egr_axi securityAttribute false
set_interface_property egr_axi userData false
set_interface_property egr_axi readIssuingCapability 16
set_interface_property egr_axi writeIssuingCapability 16
set_interface_property egr_axi combinedIssuingCapability 16
set_interface_property egr_axi enableConcurrentSubordinateAccess 0
set_interface_property egr_axi noRepeatedIdsBetweenSubordinates 0
set_interface_property egr_axi issuesINCRBursts true
set_interface_property egr_axi issuesWRAPBursts true
set_interface_property egr_axi issuesFIXEDBursts true
set_interface_property egr_axi ENABLED true
set_interface_property egr_axi EXPORT_OF ""
set_interface_property egr_axi PORT_NAME_MAP ""
set_interface_property egr_axi CMSIS_SVD_VARIABLES ""
set_interface_property egr_axi SVD_ADDRESS_GROUP ""
set_interface_property egr_axi IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property egr_axi SV_INTERFACE_TYPE ""
set_interface_property egr_axi SV_INTERFACE_MODPORT_TYPE ""

add_interface_port egr_axi egr_awid awid Output "((AXIMM_AWID_WIDTH - 1)) - (0) + 1"
set_port_property egr_awid VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port egr_axi egr_awaddr awaddr Output "((AXIMM_AWADDR_WIDTH - 1)) - (0) + 1"
add_interface_port egr_axi egr_awlen awlen Output 8
add_interface_port egr_axi egr_awsize awsize Output 3
add_interface_port egr_axi egr_awburst awburst Output 2
add_interface_port egr_axi egr_awlock awlock Output 1
set_port_property egr_awlock VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port egr_axi egr_awcache awcache Output 4
add_interface_port egr_axi egr_awprot awprot Output 3
add_interface_port egr_axi egr_awvalid awvalid Output 1
add_interface_port egr_axi egr_awready awready Input 1
add_interface_port egr_axi egr_wdata wdata Output "((AXIMM_WDATA_WIDTH - 1)) - (0) + 1"
add_interface_port egr_axi egr_wstrb wstrb Output "(((AXIMM_WDATA_WIDTH / 8) - 1)) - (0) + 1"
add_interface_port egr_axi egr_wlast wlast Output 1
add_interface_port egr_axi egr_wvalid wvalid Output 1
add_interface_port egr_axi egr_wready wready Input 1
add_interface_port egr_axi egr_bid bid Input "((AXIMM_BID_WIDTH - 1)) - (0) + 1"
set_port_property egr_bid VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port egr_axi egr_bresp bresp Input 2
add_interface_port egr_axi egr_bvalid bvalid Input 1
add_interface_port egr_axi egr_bready bready Output 1
add_interface_port egr_axi egr_arid arid Output "((AXIMM_ARID_WIDTH - 1)) - (0) + 1"
set_port_property egr_arid VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port egr_axi egr_araddr araddr Output "((AXIMM_ARADDR_WIDTH - 1)) - (0) + 1"
add_interface_port egr_axi egr_arlen arlen Output 8
add_interface_port egr_axi egr_arsize arsize Output 3
add_interface_port egr_axi egr_arburst arburst Output 2
add_interface_port egr_axi egr_arlock arlock Output 1
set_port_property egr_arlock VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port egr_axi egr_arcache arcache Output 4
add_interface_port egr_axi egr_arprot arprot Output 3
add_interface_port egr_axi egr_arvalid arvalid Output 1
add_interface_port egr_axi egr_arready arready Input 1
add_interface_port egr_axi egr_rid rid Input "((AXIMM_RID_WIDTH - 1)) - (0) + 1"
set_port_property egr_rid VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port egr_axi egr_rdata rdata Input "((AXIMM_RDATA_WIDTH - 1)) - (0) + 1"
add_interface_port egr_axi egr_rresp rresp Input 2
add_interface_port egr_axi egr_rlast rlast Input 1
add_interface_port egr_axi egr_rvalid rvalid Input 1
add_interface_port egr_axi egr_rready rready Output 1


# 
# connection point igr_axi
# 
add_interface igr_axi axi4 end
set_interface_property igr_axi associatedClock clk
set_interface_property igr_axi associatedReset rst
set_interface_property igr_axi wakeupSignals false
set_interface_property igr_axi uniqueIdSupport false
set_interface_property igr_axi poison false
set_interface_property igr_axi traceSignals false
set_interface_property igr_axi isTranslator false
set_interface_property igr_axi dataCheck false
set_interface_property igr_axi addressCheck false
set_interface_property igr_axi securityAttribute false
set_interface_property igr_axi userData false
set_interface_property igr_axi readAcceptanceCapability 16
set_interface_property igr_axi writeAcceptanceCapability 16
set_interface_property igr_axi combinedAcceptanceCapability 16
set_interface_property igr_axi readDataReorderingDepth 1
set_interface_property igr_axi bridgesToMaster ""
set_interface_property igr_axi dfhFeatureGuid 0
set_interface_property igr_axi dfhGroupId 0
set_interface_property igr_axi dfhParameterId ""
set_interface_property igr_axi dfhParameterName ""
set_interface_property igr_axi dfhParameterVersion ""
set_interface_property igr_axi dfhParameterData ""
set_interface_property igr_axi dfhParameterDataLength ""
set_interface_property igr_axi dfhFeatureMajorVersion 0
set_interface_property igr_axi dfhFeatureMinorVersion 0
set_interface_property igr_axi dfhFeatureId 35
set_interface_property igr_axi dfhFeatureType 3
set_interface_property igr_axi ENABLED true
set_interface_property igr_axi EXPORT_OF ""
set_interface_property igr_axi PORT_NAME_MAP ""
set_interface_property igr_axi CMSIS_SVD_VARIABLES ""
set_interface_property igr_axi SVD_ADDRESS_GROUP ""
set_interface_property igr_axi IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property igr_axi SV_INTERFACE_TYPE ""
set_interface_property igr_axi SV_INTERFACE_MODPORT_TYPE ""

add_interface_port igr_axi igr_awid awid Input "((AXIMM_AWID_WIDTH - 1)) - (0) + 1"
set_port_property igr_awid VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port igr_axi igr_awaddr awaddr Input "((AXIMM_AWADDR_WIDTH - 1)) - (0) + 1"
add_interface_port igr_axi igr_awlen awlen Input 8
add_interface_port igr_axi igr_awsize awsize Input 3
add_interface_port igr_axi igr_awburst awburst Input 2
add_interface_port igr_axi igr_awlock awlock Input 1
set_port_property igr_awlock VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port igr_axi igr_awcache awcache Input 4
add_interface_port igr_axi igr_awprot awprot Input 3
add_interface_port igr_axi igr_awvalid awvalid Input 1
add_interface_port igr_axi igr_awready awready Output 1
add_interface_port igr_axi igr_wdata wdata Input "((AXIMM_WDATA_WIDTH - 1)) - (0) + 1"
add_interface_port igr_axi igr_wstrb wstrb Input "(((AXIMM_WDATA_WIDTH / 8) - 1)) - (0) + 1"
add_interface_port igr_axi igr_wlast wlast Input 1
add_interface_port igr_axi igr_wvalid wvalid Input 1
add_interface_port igr_axi igr_wready wready Output 1
add_interface_port igr_axi igr_bid bid Output "((AXIMM_BID_WIDTH - 1)) - (0) + 1"
set_port_property igr_bid VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port igr_axi igr_bresp bresp Output 2
add_interface_port igr_axi igr_bvalid bvalid Output 1
add_interface_port igr_axi igr_bready bready Input 1
add_interface_port igr_axi igr_arid arid Input "((AXIMM_ARID_WIDTH - 1)) - (0) + 1"
set_port_property igr_arid VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port igr_axi igr_araddr araddr Input "((AXIMM_ARADDR_WIDTH - 1)) - (0) + 1"
add_interface_port igr_axi igr_arlen arlen Input 8
add_interface_port igr_axi igr_arsize arsize Input 3
add_interface_port igr_axi igr_arburst arburst Input 2
add_interface_port igr_axi igr_arlock arlock Input 1
set_port_property igr_arlock VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port igr_axi igr_arcache arcache Input 4
add_interface_port igr_axi igr_arprot arprot Input 3
add_interface_port igr_axi igr_arvalid arvalid Input 1
add_interface_port igr_axi igr_arready arready Output 1
add_interface_port igr_axi igr_rid rid Output "((AXIMM_RID_WIDTH - 1)) - (0) + 1"
set_port_property igr_rid VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port igr_axi igr_rdata rdata Output "((AXIMM_RDATA_WIDTH - 1)) - (0) + 1"
add_interface_port igr_axi igr_rresp rresp Output 2
add_interface_port igr_axi igr_rlast rlast Output 1
add_interface_port igr_axi igr_rvalid rvalid Output 1
add_interface_port igr_axi igr_rready rready Input 1


# 
# connection point csr_vector_addr
# 
add_interface csr_vector_addr conduit end
set_interface_property csr_vector_addr associatedClock ""
set_interface_property csr_vector_addr associatedReset ""
set_interface_property csr_vector_addr ENABLED true
set_interface_property csr_vector_addr EXPORT_OF ""
set_interface_property csr_vector_addr PORT_NAME_MAP ""
set_interface_property csr_vector_addr CMSIS_SVD_VARIABLES ""
set_interface_property csr_vector_addr SVD_ADDRESS_GROUP ""
set_interface_property csr_vector_addr IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property csr_vector_addr SV_INTERFACE_TYPE ""
set_interface_property csr_vector_addr SV_INTERFACE_MODPORT_TYPE ""

add_interface_port csr_vector_addr csr_vector_addr csr_vector_addr Input "((AXIMM_AWADDR_WIDTH - 1)) - (0) + 1"


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""
set_interface_property clk IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clk SV_INTERFACE_TYPE ""
set_interface_property clk SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clk clk clk Input 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""
set_interface_property rst IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property rst SV_INTERFACE_TYPE ""
set_interface_property rst SV_INTERFACE_MODPORT_TYPE ""

add_interface_port rst rst reset Input 1

